### PR TITLE
Fix package version issues (jupyterlab, pypdb, rdkit, black-nb)

### PR DESCRIPTION
**Pull request by dominiquesydow**
## Description

Pin JLab 2 because JLab 3 is not compatible yet with `nglview` (details [here](https://github.com/volkamerlab/teachopencadd/issues/80)) and fix problems with `pypdb` and `rdkit` uncovered by the CI along the way :)

## TODOs

- [x] Pin JLab using `jupyterlab=2` in 3 environment files :) -- OUTDATED
  - `devtools/conda-envs/test_env.yml`
  - `devtools/conda-envs/users_env.yml`
  - `environment.yml`
 - [x] Upgrade to JLab 3
- [x] CI shows `black-nb` error: "error: cannot format teachopencadd/talktorials/T002_compound_adme/talktorial.ipynb: INTERNAL ERROR: Black produced different code on the second pass of the formatter."
- [x] T002/T004/T006: `AttributeError: module 'pandas.io.formats.format' has no attribute '_get_adjustment'` (`rdkit`'s `PandasTools`), see https://github.com/rdkit/rdkit/issues/3701
- [ ] T008: `AttributeError: module 'pypdb' has no attribute 'make_query'`, `AttributeError: module 'pypdb' has no attribute 'get_ligands'`, check with https://github.com/volkamerlab/teachopencadd/issues/77
- [ ] T009: Result from T008 fail? `EmptyDataError: No columns to parse from file`
- [ ] T010: Again `pypdb` problems
- [x] black-nb needs a new release on PyPI -- pending

## Status

- [x] Ready to go

### CODE REVIEW

**Comment by dominiquesydow** [comment]
Regarding the `black-nb` error during the CI. Testing this locally on `master`:

```bash
(toctest) d@c: ~/Documents/GitHub/TeachOpenCADD on master [$]
$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
(toctest) d@c: ~/Documents/GitHub/TeachOpenCADD on master [$]
$ black-nb -l 99 teachopencadd/
    24 cells left unchanged.
error: cannot format teachopencadd/talktorials/T002_compound_adme/talktorial.ipynb: INTERNAL ERROR: Black produced different code on the second pass of the formatter.
error: cannot format teachopencadd/talktorials/T015_protein_ligand_docking/talktorial.ipynb: INTERNAL ERROR: Black produced different code on the second pass of the formatter.
reformatted teachopencadd/talktorials/T016_protein_ligand_interactions/talktorial.ipynb
    2 cells reformatted, 20 cells left unchanged.
All done! ✨ 🍰 ✨
1 file reformatted, 13 files left unchanged, 2 files failed to reformat.
(toctest) d@c: ~/Documents/GitHub/TeachOpenCADD on master [!$]
$ git diff teachopencadd/talktorials/T002_compound_adme/talktorial.ipynb
(toctest) d@c: ~/Documents/GitHub/TeachOpenCADD on master [!$]
$ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   teachopencadd/talktorials/T006_compound_maximum_common_substructures/talktorial.ipynb
	modified:   teachopencadd/talktorials/T016_protein_ligand_interactions/talktorial.ipynb

no changes added to commit (use "git add" and/or "git commit -a")
(toctest) d@c: ~/Documents/GitHub/TeachOpenCADD on master [!$]
$ git diff teachopencadd/talktorials/T006_compound_maximum_common_substructures/talktorial.ipynb
diff --git a/teachopencadd/talktorials/T006_compound_maximum_common_substructures/talktorial.ipynb b/teachopencadd/talktorials/T006_compound_maximum_common_substructures/talktorial.ipynb
index 1d2e999..c0c4cb1 100644
--- a/teachopencadd/talktorials/T006_compound_maximum_common_substructures/talktorial.ipynb
+++ b/teachopencadd/talktorials/T006_compound_maximum_common_substructures/talktorial.ipynb
@@ -967,4 +967,4 @@
  },
  "nbformat": 4,
  "nbformat_minor": 4
-}
\ No newline at end of file
+}
```

**Comment by dominiquesydow** [comment]
Unstable formatting reported here: https://github.com/psf/black/labels/unstable%20formatting

**Comment by jaimergp** [comment]
Investigating :)

**Comment by dominiquesydow** [comment]
Pytest fails overview (probably for another PR):

- T002/T004/T006: `AttributeError: module 'pandas.io.formats.format' has no attribute '_get_adjustment'` (`rdkit`'s `PandasTools`), see https://github.com/rdkit/rdkit/issues/3701
- T008: `AttributeError: module 'pypdb' has no attribute 'make_query'`, `AttributeError: module 'pypdb' has no attribute 'get_ligands'`, check with https://github.com/volkamerlab/teachopencadd/issues/77
- T009: Result from T008 fail? `EmptyDataError: No columns to parse from file`
- T010: Again `pypdb` problems

**Comment by dominiquesydow** [comment]
> Investigating :)

I am inclined to say "Thank, God!" :relieved: _Thank you_, @jaimergp!

**Comment by jaimergp** [comment]
I am excluding T002 from the black checks because it's not like we are going to change it much. I'll open an issue so we don't forget removing that exclusion.

**Comment by jaimergp** [comment]
Thanks for the issues. We can use this PR if you want, or open different ones. As you wish :)

**Comment by dominiquesydow** [comment]
> Thanks for the issues. We can use this PR if you want, or open different ones. As you wish :)

At this point I am happy to do all the fixing here :laughing:

**Comment by jaimergp** [comment]
Yeah, let's keep it here. Rename the PR to address the new purpose and that's it :)

**Comment by jaimergp** [comment]
Ok, so a summary of these changes:

- New RDKit fixed the pandas issue, so no pinning needed
- New nglview fixed the Jupyter Lab 3, so no pinning needed
- Black-nb now fixed but release on PyPI not yet available (only on GH).
- PyPDB still giving trouble... that might require some extra work.

I suggest waiting for black-nb and then merging this PR. Address pypdb stuff separately.

**Comment by jaimergp** [comment]
New black-nb is out, compatible with latest black. Guess what, our problem with T002 was not solved. So I dug deeper. Turns out some sanitization necessary for Jupyter notebooks (trailing `?` help, `%` magics, `!` shell commands) gets in the way of the validation, and pay attention: if a comment ends up in `?`, it triggers a false validation error!

So as long as remove the trailing question mark (or add something else after it), it works again!

I'll submit the fix as a PR for them, but for now I have reworded the offending comments to remove the trailing question mark.

**Comment by dominiquesydow** [comment]
Wow, thanks a lot, @jaimergp!

**Comment by jaimergp** [comment]
Ok, nice, that worked! Now black complains but without erroring out. I will reformat all the notebooks in the T11 merge event anyway, so I'll merge this as is.

**Pull request merged**
