### PR TITLE
Fix pandas failure

### PR DESCRIPTION
**Pull request by schallerdavid**
## Description
This PR investigates recent failures of the CI when using the PandasTools from RDKit (#204).

## Todos
- [x] Identify problem

## Status
- [x] Ready to go

### CODE REVIEW

**Comment by schallerdavid** [comment]
Hey @dominiquesydow and @t-kimber ,

I think I found the issue. It is about changes to PandasTools with the new RDKit release. However, I am having a hard time getting all CI runs green. It's mostly about a connection problem when requesting data online. This is completely random across the different Python versions and operating systems tested. Did you also observe such behavior recently?

**Comment by dominiquesydow** [comment]
Hi @schallerdavid, thank you for the fix!!

Could you please raise an issue that reminds us to un-pin `rdkit` again, once the problem is solved on their end?

Regarding the connection problems - I started to collect frequent trouble-makers here to address them in one go in a separate PR:
https://github.com/volkamerlab/teachopencadd/issues/199

For this PR, let's merge even if we have the usual connection CI problems.

**Review by dominiquesydow — APPROVED** [review]
Good to go from my side, thank you!

**Comment by schallerdavid** [comment]
@dominiquesydow I can't merge without all tests passing. Do you have such power :) ?

I will give it a few more attempts.

**Comment by t-kimber** [comment]
> @dominiquesydow I can't merge without all tests passing. Do you have such power :) ?
> 
> I will give it a few more attempts.

Hi @schallerdavid , don't you have this option ? 
 - [ ] Use your administrator privileges to merge this pull request.

**Comment by dominiquesydow** [comment]
I have the power :) I will merge now (the tests will rerun anyways after the merge, no need to wait).

**Comment by schallerdavid** [comment]
Ohh, just saw you merged something, maybe it was for this reason.

**Comment by dominiquesydow** [comment]
@schallerdavid - I just checked, @t-kimber is right, you are an admin according to TOC's GH settings; so you can merge with admin rights in the future. You have the power, too :)

**Pull request merged**
