### PR TITLE
Base branch for new talktorials

### PR DESCRIPTION
**Pull request by jaimergp**
## Description

This is the base PR for the next round of new talktorials.
Some notebooks involve refactoring and extension of the former T11 talktorial series. 
Supersedes #69 originally opened by @dominiquesydow.

## TODOs

- [x] Swap indices `012_query_pubmed`/`013_query_klifs` > `012_query_klifs`/`013_query_pubmed`
- [x] Talktorial splits
  - [x] Split former T11a into T012 and T013 @dominiquesydow
  - [x] Split former T11c into T016 and T017 @jaimergp
- [x] New and extended talktorials
  - [x] **T000** - Talktorial template @dominiquesydow #85 
  - [x] **T011** - Online APIs/webservices (former T11) @jaimergp #84 
  - [x] **T012** - Data acquisition from KLIFS (former T11a: only KLIFS) @dominiquesydow #79 
  - [x] **T013** - Data acquisition from PubChem (former T11a: only PubChem) @yonghui-cc #81 
  - [x] **T014** - Binding site detection (former T11b: only binding site detection) @AndreaVolkamer #86 
  - [x] **T015** - Protein-ligand docking (former T11b: only preparation and docking) @schallerdavid #82
  - [x] **T016** - Protein-ligand interactions (former T11c: only protein-ligand interactions) @t-kimber #75
  - [x] **T017** - Advanced NGLview & widget usage (former T11c: only NGLview and widget stuff) @jaimergp  #92 
  - [x] ~~**T018** - Pipeline (former T11a-c: full pipeline without details on individual steps but reference to T012-17)~~ (_postponed_) https://github.com/volkamerlab/teachopencadd/pull/125
  - [x] **T019** - Molecular dynamics simulations @Mika-Le #56
  - [x] **T020** - Analyzing molecular dynamics simulations @Mika-Le #76
  - [x] **T021** - One-hot encoding @sakshimisra #54 
  - [x] **T022** - Ligand-based screening: Neural networks @sakshimisra #64 
- [x] Fix `pypdb`-related talktorials T008 and T010
- [x] **T011-T018** - Talktorial review by @AndreaVolkamer #106
- [x] **T014**: Can we remove TODO? Check if `biopandas` 0.2.8 can be installed. https://github.com/rasbt/biopandas/issues/86
- [x] ~Make sure Binder runs #130~ (_postponed_)
- [x] **T001**: Update frozen dataset strategy: https://github.com/volkamerlab/teachopencadd/issues/134
- [x] **T019**: Remove from Windows CI: https://github.com/volkamerlab/teachopencadd/issues/136
- [x] Add disclaimer to README linking back to old version of repo

## Questions

- [x] How do I start ? Check out the PR template: https://github.com/volkamerlab/teachopencadd/issues/41!

## Status

- [x] Ready to go

### CODE REVIEW

**Comment by schallerdavid** [comment]
How do we want to present docking results? With widget or without? Would be good if the visualization is as fancy as possible but should also look good in the html version.

[Here](https://github.com/volkamerlab/CADDSeminar_2020/blob/T06-MT/notebooks/06_molecularDocking/T06_molecularDocking.ipynb) is a version created from one of our students during the CADD Seminar.

**Comment by jaimergp** [comment]
All opened PRs depending on this one have been merged. Now I need to work out those `pypdb` refactors in a separate PR and then we can start reviewing all the notebooks, @AndreaVolkamer!

**Comment by dominiquesydow** [comment]
Short wrap-up after working on CI problems; T011, T014 and `black-nb` fixed - what problems are left?

- T010 is still a problem because of #90 
- CI windows 3.6 failed to setup `conda` > maybe in luck next time (happens to my other repos sometimes)
- T015 is a problem under Ubuntu and MacOS **Python 3.6** (not Ubuntu 3.9), pasting error below to pick this up later

```
_ teachopencadd/talktorials/T015_protein_ligand_docking/talktorial.ipynb::Cell 11 _
[gw0] darwin -- Python 3.6.13 /usr/local/miniconda/envs/teachopencadd/bin/python
Notebook cell execution failed
Cell 11: Cell execution caused an exception

Input:
output_text = run_smina(
    DATA / "ligand.pdbqt",
    DATA / "protein.pdbqt",
    DATA / "docking_poses.sdf",
    pocket_center,
    pocket_size,
)
print(output_text)

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-12-12f5c1e49967> in <module>
      4     DATA / "docking_poses.sdf",
      5     pocket_center,
----> 6     pocket_size,
      7 )
      8 print(output_text)

<ipython-input-11-996ac07001ea> in run_smina(ligand_path, protein_path, out_path, pocket_center, pocket_size, num_poses, exhaustiveness)
     53             str(exhaustiveness),
     54         ],
---> 55         text=True,
     56     )
     57     return output_text

TypeError: __init__() got an unexpected keyword argument 'text'
```

**Comment by dominiquesydow** [comment]
@schallerdavid if that docking notebook error above is somehow familiar to you I am happy about pointers :)

**Comment by schallerdavid** [comment]
@dominiquesydow I can investigate this.

**Comment by dominiquesydow** [comment]
@schallerdavid, thanks so much for fixing T015 :heart:

**Comment by dominiquesydow** [comment]
Quick CI issue update:

- T010 is still a problem because of #90 > working on that today
- CI windows 3.6 still fails to setup `conda` > no clue right now, fix other CI fails first
- T017 has this time a `TimeoutError`, probably simply because of the PDB > add `redo` decorator to cell? 
  ```
    _ teachopencadd/talktorials/T017_advanced_nglview_usage/talktorial.ipynb::Cell 56 _
  [gw0] linux -- Python 3.6.13 /usr/share/miniconda/envs/teachopencadd/bin/python
  Notebook cell execution failed
  Cell 56: Cell execution caused an exception
  
  Input:
  view = nv.show_pdbid("2G1T")  # Human ABL1 kinase
  view
  ```

**Comment by dominiquesydow** [comment]
@jaimergp, short update from my side :)

Done:
- **T001-T010**: Sanity-checked text
- **T001-T022**: Checked website rendering
- **CI / Ubuntu and MacOS**: Fixed (thanks @schallerdavid for your help with T015)
- **CI / READMEs**: Fixed

TODO:
- **CI Docs**: Locally they run fine, not sure where the CI error comes from; there is one warning `/home/runner/work/teachopencadd/teachopencadd/docs/talktorials/T017_advanced_nglview_usage.nblink:3258: WARNING: Pygments lexer name 'cmd' is not known`
- **CI / Windows**: [Conda install fails](https://github.com/volkamerlab/teachopencadd/pull/74/checks?check_run_id=2583580685)
- **Website**: For the new talktorials, the "previous" and "next" buttons are mixed up. Can you give me a pointer where to go looking? Example for T011:
  image

**Comment by jaimergp** [comment]
> CI / Windows: Conda install fails

This is `ambertools` being missing on Windows. This is pulled from `openmmforcefields`, which we use in the MD notebook, T020. Maybe we can install it manually there, like we do with Colab, so the whole project does not stop working on Windows just because of a single talktorial. A disclaimer that it won't work on Windows might help too.

I'll look into the `cmd` lexer. No clue about the website navigation issue.

**Comment by jaimergp** [comment]
Yay `docs` is green now!

**Comment by jaimergp** [comment]
Oh wow we have full greens in Linux now (besides the inevitable timeout here and there!).

Windows shows some errors, though:

* T011 and [T012](https://github.com/volkamerlab/teachopencadd/pull/74/checks?check_run_id=2600210648#step:8:98): `ValueError: stat: path too long for Windows`. Itt's an issue with NGLView. Basically, we are trying to compare whether the PDB contents as a string is a valid path in disk. Since it's too long of a path, this will fail in Windows instead of saying "hey, no, this is not a file". We can submit a patch to `nglview` or provide a workaround ourselves, since we know it's not a path, we can wrap it in a `io.StringIO` object.
* [T016](https://github.com/volkamerlab/teachopencadd/pull/74/checks?check_run_id=2600210648#step:8:357): it fails due to a diff issue. A nitrogen is recognized differently on Windows than Unix (?). Might have to do with different versions installed.

**Comment by jaimergp** [comment]
T11/T12 should be fixed by https://github.com/nglviewer/nglview/pull/977 ;)

**Comment by dominiquesydow** [comment]
@AndreaVolkamer, the talktorials are ready from my side for you to read/review.

**Comment by dominiquesydow** [comment]
@schallerdavid could you please take a look at the CI fail for T016 concerning `plip`, potentially propagating from the MDAnalysis 3.0.0 update:
https://github.com/volkamerlab/teachopencadd/runs/3481452711#step:8:270

The chain IDs are apparently set to X (instead of A). Have you encountered this already in your plipify project?

**Comment by schallerdavid** [comment]
> @schallerdavid could you please take a look at the CI fail for T016 concerning `plip`, potentially propagating from the MDAnalysis 3.0.0 update:
> https://github.com/volkamerlab/teachopencadd/runs/3481452711#step:8:270
> 
> The chain IDs are apparently set to X (instead of A). Have you encountered this already in your plipify project?

You are correct, it's all about the chain name being changed to "X". We did not touch plipify for quite a while, so I am not sure how this change affects this project. Anyway, OpenCADD is retrieving the PDB entry in MMTF format. In the MDAnalysis [docs](https://userguide.mdanalysis.org/stable/formats/index.html) they list all read attributes, chain ID, and element information are not read. I rerun the notebook and pushed the updated version. Let's hope the tests pass.

**Comment by dominiquesydow** [comment]
We have passing tests incl. Windows! Fails for Ubuntu are only connection timeouts! :partying_face: 
I will merge this PR now :) 

We can deal with `conda` packaging, website polishing ect. (see #137) in new and more digestible PRs.

A big THANK YOU to everyone who contributed new talktorials in this PR!
Also thanks to @schallerdavid for helping me out to fix the CI problems!

**Pull request merged**
