### PR TITLE
T017 - Advanced NGLview usage

### PR DESCRIPTION
**Pull request by jaimergp**
# Details

* Talktorial ID: 017
* Title: Advanced NGLview usage
* Original authors: Jaime Rodríguez-Guerra
* Reviewer(s): Dominique Sydow
* Date of review:

# Content review

* Potential labels or categories (e.g. machine learning, small molecules, online APIs): XXXXXXXX
* One line summary: XXXXXXXXXX
* [ ] The table of contents reflects the talktorial story-line; order of #, ##, ### headers is correct
* [ ] URLs are linked with meaningful words, instead of pasting the URL directly or linking words like `here`.
* [ ] I have spell-checked the notebook
* [ ] Images have enough resolution to be rendered with quality, without being _too_ heavy.
* [ ] All figures have a description
* [ ] Markdown cell content is still in-line with code cell output (whenever results are discussed)
* [ ] I have checked that cell outputs are not incredibly long (this applies also to `DataFrames`)
* [ ] Formatting looks correctly on the Sphinx render (bold, italics, figure placing)

# Code review

* Time it took to execute (approx.):
* [ ] Variable and function names follow snake case rules (e.g. `a_variable_name` vs `aVariableName`)
* [ ] Spacing follows PEP8 (run Black on the code cells if needed)
* [ ] Code line are under 99 characters each (run `black -l 99`)
* [ ] Comments are useful and well placed
* [ ] There are no unpythonic idioms like `for i in range(len(list))` (see slides)
* [ ] All 3rd party dependencies are listed at the top of the notebook
* [ ] I have marked all code cell with output referenced in markdown cells with the label `# TODO: CI`
* [ ] I have identified potential candidates for a code refactor / useful functions
* [ ] All `import ...` lines are at the top (practice part) cell, ordered by standard library / 3rd party packages / our own (`teachopencadd.*`)
* [ ] I have update the relative paths to absolute paths.
* List here unfamiliar libraries you find in the imports and their intended use:

### CODE REVIEW

**Comment by dominiquesydow** [comment]
Hi @jaimergp, 

I had a quick look at the table of contents as requested - very well done!

First things first:
- Love the video (of course) - and the slow intro on interactive controls
- Excellent idea to have "troubleshooting tips"!!!

Things that come to mind for 1.3.2:
- [As part of 1.3.2.3?] Selection algebra (with link to their [documentation](https://nglviewer.org/ngl/api/manual/usage/selection-language.html))
- [As part of 1.3.2.3?] Show how to use custom color schemes (coloring residues by some user values): Some like this in a minimal example ([cell 31](https://github.com/volkamerlab/kissim_app/blob/nb-fingerprints/notebooks/fingerprints/fingerprint.ipynb))
- GUI usage with `viewer.display(gui=True)` - it is super convenient for many quick tasks and people should know that it exists (even when you might not comment much on it)
- Simple example on how you can add e.g. spheres (e.g. show protein center)
- Mention that there is a plethora of `nglview.show_...` options (e.g. how to load trajectories, cross-referencing our MD talktorials)

W.r.t. 1.3.3 I do not know really what will live behind the titles, so here is what I would like to learn maybe?
- How can I layout an `nglview` window with a second window where I can choose between (toogle on/off)
  - different structures to be shown 
  - different coloring schemes which represent different features (as in highlight all HBDs or HBAs or ...)
- How can I manipulate the label for residues (the labels that appear when I hover over a residue)?

Looking forward to this notebook - it will be helpful for everyone who starts out using `nglview` :)

**Comment by jaimergp** [comment]
Only theory missing! 🥳

**Comment by jaimergp** [comment]
Theory done. I need to update the table of contents and polish for typos and so on, but this will be ready for review later today!

**Comment by jaimergp** [comment]
@dominiquesydow, this is ready for review!

**Comment by dominiquesydow** [comment]
Excellent! On my agenda for tomorrow :)

**Comment by dominiquesydow** [comment]
@jaimergp, this notebook is amazing on so many levels! My brain is fried from all the new things I learnt. Great job! And thank you :heart:

**Comment by jaimergp** [comment]
@dominiquesydow, thanks for the thorough review!!

Took me ages but I have started reviewing your comments :) I have resolved most of the feedback, but there are some outstanding issues I need some help and/or clarification! Thanks again!

**Comment by dominiquesydow** [comment]
Excellent! 

Unsure what the open issues are - I did comment on hopefully everything you wrote. Basically everything a ready-to-go :) 

This talktorial helped me tremendously in another project with NGLview and a lot of `ipywidget`-enabled plots, so thank you.

**Comment by jaimergp** [comment]
Ok, we are done!

**Pull request merged**
