### PR TITLE
T004 review

### PR DESCRIPTION
**Pull request by yonghui-cc**
# Details

* Talktorial ID: T004
* Title: Ligand-based screening: compound similarity
* Original authors: Andrea Morger and Franziska Fritz
* Reviewer(s): Yonghui, Dominique
* Date of review: 29.09.2020
* [ReviewNB link](https://app.reviewnb.com/volkamerlab/TeachOpenCADD/pull/48/files/)

# Content review

* Potential labels or categories (e.g. machine learning, small molecules, online APIs): _molecular fingerprint, ligand-based virtual screening, MACCS fingerprint, Morgan fingerprint, Tanimoto similarity, Dice similarity_
* One line summary: _Ligand-based virtual screening by comparing the similarity of molecules with their molecular fingerprints._
* [x] The table of contents reflects the talktorial story-line; order of #, ##, ### headers is correct
* [x] URLs are linked with meaningful words, instead of pasting the URL directly or linking words like `here`.
* [x] I have spell-checked the notebook
* [x] Images have enough resolution to be rendered with quality, without being _too_ heavy.
* [x] All figures have a description
* [x] Markdown cell content is still in-line with code cell output (whenever results are discussed)
* [x] I have checked that cell outputs are not incredibly long (this applies also to `DataFrames`)
* [x] Formatting looks correctly on the Sphinx render (bold, italics, figure placing)

# Code review

* Time it took to execute (approx.):
* [x] Variable and function names follow snake case rules (e.g. `a_variable_name` vs `aVariableName`)
* [x] Spacing follows PEP8 (run Black on the code cells if needed)
* [x] Code line are under 99 characters each (run `black -l 99`)
* [x] Comments are useful and well placed
* [x] There are no unpythonic idioms like `for i in range(len(list))` (see slides)
* [x] All 3rd party dependencies are listed at the top of the notebook
* [x] I have marked all code cell with output referenced in markdown cells with the label `# TODO: CI`
* [x] I have identified potential candidates for a code refactor / useful functions
* [x] All `import ...` lines are at the top (practice part) cell, ordered by standard library / 3rd party packages / our own (`teachopencadd.*`)
* [x] I have update the relative paths to absolute paths.
Please add the following lines to the top of the notebook and use those paths

### CODE REVIEW

**Comment by dominiquesydow** [comment]
Hi @yonghui-cc, I left my review here via ReviewNB - let me know if you have questions. We can also video call to go over cells that are a bit more difficult to discuss via the pull request interface here.

**Review by dominiquesydow — COMMENTED** [review]
Hi @yonghui-cc, I left my review here via ReviewNB - let me know if you have questions. We can also video call to go over cells that are a bit more difficult to discuss via the pull request interface here.

**Comment by yonghui-cc** [comment]
> View / edit / reply to [this conversation](https://app.reviewnb.com/volkamerlab/TeachOpenCADD/pull/48/discussion/) on ReviewNB
> 
> _dominiquesydow commented on 2020-10-01T14:20:18Z_
> ----------------------------------------------------------------
> 
> Why `[:1]` and not `[0]` ? Happens also in other cells below.

they are different. there was err if change [:1] to [0]. I guess [:1] output a list, but [0] not.

**Comment by jaimergp** [comment]
> I would like to test the picture with need to be saved

This is going to be complicated. Even if visually similar, the encoded PNG might feature different compression schemes we can't control. Instead of testing the image, we can achieve similar functionality if we test the values represented. If possible, it's easier to test for scalars (e.g. the fingerprints).

**Comment by yonghui-cc** [comment]
> > I would like to test the picture with need to be saved
> 
> This is going to be complicated. Even if visually similar, the encoded PNG might feature different compression schemes we can't control. Instead of testing the image, we can achieve similar functionality if we test the values represented. If possible, it's easier to test for scalars (e.g. the fingerprints).

Thanks! I will remove the '#TODO: CI' for the picture and leave only one CI test request at the end of the notebook to test the final output.

**Comment by dominiquesydow** [comment]
@yonghui-cc, thanks for your update! I will not be able to review this notebook again before tomorrow (note for @jaimergp).

**Comment by dominiquesydow** [comment]
@yonghui-cc - quick question: 
Why did you delete the sections "Molecular similarity" and "Molecular descriptors"? If there was no reason for it, I will add them back, ok?

**Comment by dominiquesydow** [comment]
I updated the following:

## Aim of this talktorial (was correct)
### Contents in Theory (was: ### Theory)
### Contents in Practical (was: ### Practical)
### References (was: ## References)

Added "Theory" heading (that one was gone?).
Added back the sections "Molecular similarity" and "Molecular descriptors".
Moved each section in "Theory" into a separate cell so that they will show up in the TOC.

**Comment by dominiquesydow** [comment]
@yonghui-cc, thank you very much for the update! I went though the notebook in more detail this time and commented on text and more potential pythonic code options. Let me know if you have questions.

**Comment by yonghui-cc** [comment]
@dominiquesydow, thank you for your nice review and suggestion. I just updated the notebook, it's ready to merge if there are no more questions.

**Comment by dominiquesydow** [comment]
@yonghui-cc, I went over the notebook one more time to refactor some code bits. This notebook is ready to be merged from my side. Thank you for your work on this talktorial! Do you want to have a final look?

**Review by dominiquesydow — APPROVED** [review]

**Comment by yonghui-cc** [comment]
@dominiquesydow, @jaimergp, Great! the notebook is ready to be merged from my side too.

**Pull request merged**
