### PR TITLE
Reenable Binder

### PR DESCRIPTION
**Pull request by jaimergp**
I wanted to get rid of some environment.yml duplication but didn't remember that Binder depended on that. I've fixed that problem now, mentioned in #100 

The Binder env is now under `.binder/environment.yml`, which is a symlink to `devtools/test_env.yml`. Notice that `test_env.yml` is not under `conda-envs` anymore so we can use the same relative path for TeachOpenCADD (`../` instead of `../../`).

@dominiquesydow, you ok with these changes?

### CODE REVIEW

**Comment by dominiquesydow** [comment]
@jaimergp thanks for managing this issue! 

Removing the `conda-envs` layer seems good to me, trying to understand `other-conda-envs` tough.

Is it necessary because we need a TOC URL (instead of file path) for generating the docs? 
Might be removed once there is a `teachopencadd` package?

---

Which env used where?

https://github.com/volkamerlab/teachopencadd/blob/7e60b148fabed4cdd76b3c11d64337cbf638d7e7/devtools/other-conda-envs/users_env.yml#L52-L53
used for docs

and

https://github.com/volkamerlab/teachopencadd/blob/7e60b148fabed4cdd76b3c11d64337cbf638d7e7/devtools/test_env.yml#L52-L53
used for GHA and Binder

**Comment by jaimergp** [comment]
`users_env.yml` is mostly for that part of the installation docs. Once we have a package, it won't be needed, yes. Hopefully soon!

**Comment by dominiquesydow** [comment]
Sounds good!

**Comment by jaimergp** [comment]
Cool, merging then!

**Pull request merged**
