### PR TITLE
T008 review

### PR DESCRIPTION
**Pull request by schallerdavid**
# Details

* Talktorial ID: 008
* Title: Query PDB
* Original authors: Anja Georgi, Majid Vafadar, Jaime Rodríguez-Guerra and Dominique Sydow
* Reviewer(s): Jaime Rodríguez-Guerra, David Schaller
* Date of review: 2020.09.21 - 2020.XX.YY
* [ReviewNB link](https://app.reviewnb.com/volkamerlab/TeachOpenCADD/pull/47/files/)

# Content review

* Potential labels or categories (e.g. machine learning, small molecules, online APIs): online APIs, proteins, small molecules
* One line summary: Query the PDB for EGFR structures, retrieve meta information and superimpose selected structures.
* [x] The table of contents reflects the talktorial story-line; order of #, ##, ### headers is correct
* [x] URLs are linked with meaningful words, instead of pasting the URL directly or linking words like `here`.
* [x] I have spell-checked the notebook
* [x] Images have enough resolution to be rendered with quality, without being _too_ heavy.
* [x] All figures have a description
* [x] Markdown cell content is still in-line with code cell output (whenever results are discussed)
* [x] I have checked that cell outputs are not incredibly long (this applies also to `DataFrames`)
* [x] Formatting looks correctly on the Sphinx render (bold, italics, figure placing)

# Code review

* Time it took to execute (approx.): 2.5 min
* [x] Variable and function names follow snake case rules (e.g. `a_variable_name` vs `aVariableName`)
* [x] Spacing follows PEP8 (run Black on the code cells if needed)
* [x] Code line are under 99 characters each (run `black -l 99`)
* [x] Comments are useful and well placed
* [x] There are no unpythonic idioms like `for i in range(len(list))` (see slides)
* [x] All 3rd party dependencies are listed at the top of the notebook
* [x] I have marked all code cell with output referenced in markdown cells with the label `# TODO: CI`
* [ ] I have identified potential candidates for a code refactor / useful functions
* [x] All `import ...` lines are at the top (practice part) cell, ordered by standard library / 3rd party packages / our own (`teachopencadd.*`)
* [x] I have update the relative paths to absolute paths.
* List here unfamiliar libraries you find in the imports and their intended use:

```python
HERE = Path(_dh[0])
DATA = HERE / "data"
```

### CODE REVIEW

**Comment by jaimergp** [comment]
New release of `pypdb` contains the rate-limited requests, so that means we might be able to remove the `redo` code. See https://github.com/williamgilpin/pypdb/issues/15.

**Comment by schallerdavid** [comment]
Hey @jaimergp,

ready for review.

Comments:
 - warnings from opencadd and mdanalysis

**Comment by jaimergp** [comment]
Reviewed!

**Comment by schallerdavid** [comment]
Hey @jaimergp,

this one would be ready to merge from my side.

**Pull request merged**
