### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by dominiquesydow**
Update README: 
Additionally to published Jupyter Notebooks 1-10, add information to KNIME workflows and newest Jupyter Notebook 11. Update README structure.

- [x] Update yml file (include only soft dependencies)
- [x] Check that Binder is still working
- [ ] Add TeachOpenCADD logo
- [x] Add topics figure to "Topics" section 
- [x] Add "Contact" section: Jupyter Notebooks, KNIME, contributions (contribute.volkamerlab.org)
- [x] Add "License" section: Move license info here)
- [x] Add "Citation" section: Add funders and bibtex citation
- [x] Section "Topics", add 11 and add subsections "Cheminformatics" and "Structural bioinformatics"

### CODE REVIEW

**Comment by dominiquesydow** [comment]
@jaimergp @AndreaVolkamer @morgeral @t-kimber 
Can you please have a quick check if you are ok with the updated README?

**Comment by AndreaVolkamer** [comment]
Looks great to me. Two small things: 
The figures if taken from the manuscript should be referenced accordingly. 
The citation information could be moved up a bit (before the installation instruction), so it will not be forgotten by the users.

**Comment by AndreaVolkamer** [comment]
well just oversaw that it's linked in the beginning, so forget about suggestion 2!

**Comment by dominiquesydow** [comment]
> The figures if taken from the manuscript should be referenced accordingly.

Good point, thanks! 
I removed the logo for now until it is officially published.
Regarding the topic overview figure, I added the reference to our first paper (as adaption from the more complex Figure 1).

**Pull request merged**
