### PR TITLE
fixed typo

### PR DESCRIPTION
**Pull request by rflameiro**

### CODE REVIEW

**Comment by dominiquesydow** [comment]
@rflameiro, thank you for spotting this and creating a PR!

@jaimergp - any objection merging this one on the spot? Dealing with the failing CI will need to take place in another PR.

**Review by jaimergp — APPROVED** [review]

**Comment by jaimergp** [comment]
Yep go ahead!

**Comment by rflameiro** [comment]
> @rflameiro, thank you for spotting this and creating a PR!

No problem. I don't have much experience with GitHub, and I'm wondering what those failed tests are. Was I supposed to do something before submitting the PR?

**Comment by jaimergp** [comment]
No, no, those failures are unrelated to your PR, don't worry!

**Comment by jaimergp** [comment]
Thanks @rflameiro !

**Comment by rflameiro** [comment]
Well, I thank you all for providing these notebooks! 
I'll be going through the others and I'll let you know if I find anything else.

**Pull request merged**
