### PR TITLE
T019: Fix "No template found for residue 444 (03P)"

### PR DESCRIPTION
**Pull request by dominiquesydow**
## Description
Fix problem described in #307 
Check: https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template

## Todos
Notable points that this PR has either accomplished or will accomplish.
- [x] Fix template problem - how?
- [x] Remove simtk from docstrings
- [x] Revert back to CI that tests all notebooks (not only T019)

## Status
- [x] Ready to go

### CODE REVIEW

**Comment by dominiquesydow** [comment]
Hi @schallerdavid, @Mika-Le, @AndreaVolkamer, do you have any ideas why `openmm` cannot find a template for the ligand 03P anymore? The prepared ligand still looks good to me --- what am I missing?

**Comment by AndreaVolkamer** [comment]
@schallerdavid any idea on how to fix the template issue?

**Comment by schallerdavid** [comment]
Hi everyone,

sorry for missing this for so long.

I added some comments via NBReview. Can you see those?

**Comment by AndreaVolkamer** [comment]
@schallerdavid unfortunately I cannot see them?

**Pull request merged**
