### PR TITLE
Add more obvious notice on citation in README

### PR DESCRIPTION
**Pull request by dominiquesydow**
## Description
Add more obvious notice on how to cite/highlight TeachOpenCADD usage at the top of README.

## ToDos
- [x] Add notice before TOC: "If you use TeachOpenCADD in a publication, please cite us! If you use TeachOpenCADD in class, please include a link back to our repository. In any case, please star (and tell your students to star) those repositories you consider useful for your learning/teaching activities."
- [x] Move funding paragraph from "Citation" section to a new "Funding" section.
- [x] Update/add citation links/bibtex

## Questions
None. 

## Status
- [x] Ready to go

### CODE REVIEW

**Comment by dominiquesydow** [comment]
@jaimergp, @AndreaVolkamer - I suggest to merge this directly to `master` (and not to our intermediate `package` branch), since this information should be there immediately and not later when we are finished with refactoring/packaging. What do you think?

**Comment by AndreaVolkamer** [comment]
Agree!

**Comment by jaimergp** [comment]
Agreed!

When we refactor the notebooks we might want to be a bit more _spammy_ in each notebook, like a custom header with a button like those in [this GH app](https://buttons.github.io/). But that's better addressed in a separate PR.

**Comment by dominiquesydow** [comment]
> When we refactor the notebooks we might want to be a bit more _spammy_ in each notebook, like a custom header with a button like those in [this GH app](https://buttons.github.io/). But that's better addressed in a separate PR.

Good idea, I added this to our Google Docs document on refactoring/packaging TeachOpenCADD so that we do not forget about this.

**Comment by dominiquesydow** [comment]
@AndreaVolkamer, can you please give your approval in the box above if you approve of merging?

**Pull request merged**
