### PR TITLE
T006 review

### PR DESCRIPTION
**Pull request by jaimergp**
# Details

* Talktorial ID: 006
* Title: Maximum common substructure
* Original authors: Oliver Nagel
* Reviewer(s): Jaime Rodríguez-Guerra, Andrea Volkamer
* Date of review: 2020.09.21 - 2020.XX.YY
* [ReviewNB link](https://app.reviewnb.com/volkamerlab/TeachOpenCADD/pull/43/files/)

# Content review

* Potential labels or categories (e.g. machine learning, small molecules, online APIs): XXXXXXXX
* One line summary: how to calculate the maximum substructure that a set of molecules has in common.
* [x] The table of contents reflects the talktorial story-line; order of #, ##, ### headers is correct
* [x] URLs are linked with meaningful words, instead of pasting the URL directly or linking words like `here`.
* [x] I have spell-checked the notebook
* [x] Images have enough resolution to be rendered with quality, without being _too_ heavy.
* [x] All figures have a description
* [x] Markdown cell content is still in-line with code cell output (whenever results are discussed)
* [x] I have checked that cell outputs are not incredibly long (this applies also to `DataFrames`)
* [x] Formatting looks correctly on the Sphinx render (bold, italics, figure placing)

# Code review

* Time it took to execute (approx.): <2 min
* [x] Variable and function names follow snake case rules (e.g. `a_variable_name` vs `aVariableName`)
* [x] Spacing follows PEP8 (run Black on the code cells if needed)
* [x] Code line are under 99 characters each (run `black -l 99`)
* [x] Comments are useful and well placed
* [x] There are no unpythonic idioms like `for i in range(len(list))` (see slides)
* [x] All 3rd party dependencies are listed at the top of the notebook
* [x] I have marked all code cell with output referenced in markdown cells with the label `# TODO: CI`
* [ ] I have identified potential candidates for a code refactor / useful functions
* [x] All `import ...` lines are at the top (practice part) cell, ordered by standard library / 3rd party packages / our own (`teachopencadd.*`)
* [x] I have update the relative paths to absolute paths.
* List here unfamiliar libraries you find in the imports and their intended use:

Please add the following lines to the top of the notebook and use those paths

```python
HERE = Path(_dh[0])
DATA = HERE / "data"
```

# Other issues:

* [X] Check that T005 produces deterministic outputs, since this talktorial depends on it for its analysis and it's not guaranteed we always get the same molecule set.

### CODE REVIEW

**Comment by AndreaVolkamer** [comment]
@jaimergp,  well done :)

A few open fixmes/questions/suggestions

**Important**
* in l16: we highlight by mcs2 - we probably would want to use mcs3 - but that creates an image without highlights??? Not sure what's the exact problem. 
Since I saw these warnings in the console:
`****
Pre-condition Violation
getExplicitValence() called without call to calcExplicitValence()
Violation occurred on line 196 in file /home/conda/feedstock_root/build_artifacts/rdkit_1600678001365/work/Code/GraphMol/Atom.cpp
Failed Expression: d_explicitValence > -1
****`
I tried playing around with sanitizing the molecule (Chem.SanitizeMol(mol)), didn't manage to fix it ...
* The slider does not appear in line 18 when calling `interact`??? The smarts string and image are rendered though.

**Nice to have**
* Theory: Figures in theory could be combined to one (offline), including marks A,B,C,D that match the description in the text. Or we force them to be smaller.
* Practical: If I remember correctly it should be possible to show the molecules in the grid image aligned by MCS?  

**Maybe for later**
* Since we are thinking of collections, in this notebook we refer to the original pipeline, e.g. assuming that clustering has been done before. Maybe we consider rephrasing there.

**Comment by jaimergp** [comment]
Thanks! I'll reply inline:


A few open fixmes/questions/suggestions

> **Important**
> * in l16: we highlight by mcs2 - we probably would want to use mcs3 - but that creates an image without highlights??? Not sure what's the exact problem. 
> Since I saw these warnings in the console:
> `****
> Pre-condition Violation
> getExplicitValence() called without call to calcExplicitValence()
> Violation occurred on line 196 in file /home/conda/feedstock_root/build_artifacts/rdkit_1600678001365/work/Code/GraphMol/Atom.cpp
> Failed Expression: d_explicitValence > -1
> ****`
> I tried playing around with sanitizing the molecule (Chem.SanitizeMol(mol)), didn't manage to fix it ...

Yep, I observed the same behaviour. Thanks for noticing. Issue submitted here: https://github.com/rdkit/rdkit/issues/3458

> * The slider does not appear in line 18 when calling `interact`??? The smarts string and image are rendered though.
It does appear for me. Have you installed `@jupyter-widgets/jupyterlab-manager` in Jupyter Lab?

image


> **Nice to have**
> * Theory: Figures in theory could be combined to one (offline), including marks A,B,C,D that match the description in the text. Or we force them to be smaller.

Done!

> * Practical: If I remember correctly it should be possible to show the molecules in the grid image aligned by MCS?  

Added some code adapted from [this gist](https://gist.github.com/greglandrum/82d9a86acb3b00d3bb1df502779a5810). It's buggy with partial ring match, which requires the ring matching bug to be fixed first. So for now it's disabled with the EGFR ligands (notes added in the cell).

> **Maybe for later**
> * Since we are thinking of collections, in this notebook we refer to the original pipeline, e.g. assuming that clustering has been done before. Maybe we consider rephrasing there.

We can address that when we build the first collection!

**Comment by jaimergp** [comment]
This is ready to merge if we all agree!

**Comment by AndreaVolkamer** [comment]
Great work, @jaimergp.
AGREE!

**Pull request merged**
