### PR TITLE
T018 Pipeline

### PR DESCRIPTION
**Pull request by corey-taylor**
# Details

* Talktorial ID: T018
* Title: Pipeline
* Original authors:  @corey-taylor @melvo98  @Armin-Ariamajd
* Reviewer(s): @AndreaVolkamer, @dominiquesydow
* Date of review:

# Tech
* [x] Move notebook from CADD_Seminar2021 repo (https://github.com/volkamerlab/CADDSeminar_2021/pull/7) here after contacting @melvo98 and @Armin-Ariamajd (co-authored commit)

# Content review

* Potential labels or categories (e.g. machine learning, small molecules, online APIs): small molecules, online APIs, CADD pipeline
* One line summary: Automated structure-based virtual screening pipeline
* [x] Theory: Check if text is copy-pasted from other notebooks; if so indicate with quote block and reference respective talktorials for further reading
* [x] Practical: Add class schema (architecture)
* [x] Practical: Move big classes to `utils.py` script to make reading the notebook a bit more fluent
* [x] The table of contents reflects the talktorial story-line; order of #, ##, ### headers is correct
* [x] URLs are linked with meaningful words, instead of pasting the URL directly or linking words like `here`.
* [x] I have spell-checked the notebook
* [x] Images have enough resolution to be rendered with quality, without being _too_ heavy.
* [x] All figures have a description
* [x] Markdown cell content is still in-line with code cell output (whenever results are discussed)
* [x] I have checked that cell outputs are not incredibly long (this applies also to `DataFrames`)
* [x] Formatting looks correctly on the Sphinx render (bold, italics, figure placing)
* [x] Working title: "Automated pipeline for lead optimization" (update in manuscript if title differs)

# Code review

* Time it took to execute (approx.): code execution only = 30 minutes
* [x] Variable and function names follow snake case rules (e.g. `a_variable_name` vs `aVariableName`)
* [x] Spacing follows PEP8 (run Black on the code cells if needed)
* [x] Code line are under 99 characters each (run `black -l 99`)
* [x] Comments are useful and well placed
* [x] There are no unpythonic idioms like `for i in range(len(list))` (see slides)
* [x] All 3rd party dependencies are listed at the top of the notebook
* [x] I have marked all code cell with output referenced in markdown cells with the label `# NBVAL_CHECK_OUTPUT`
* [x] I have identified potential candidates for a code refactor / useful functions
* [x] All `import ...` lines are at the top (practice part) cell, ordered by standard library / 3rd party packages / our own (`teachopencadd.*`)
* [x] I have update the relative paths to absolute paths.
* List here unfamiliar libraries you find in the imports and their intended use:
* [x] `opencadd` is not an in-house package any more; it is a third party package
* [x] Add reference to Hopkins paper mentioned in docstrings (check for other paper mentions without reference)
* [x] Run `flake8` on the Python file and `flake8-nb` on the Jupyter notebook 
* [x] Freeze PubChem CID dataset for CI; add comment on how users can unfreeze the dataset
* [x] Runs without problems on Jupyter Lab

### CODE REVIEW

**Comment by dominiquesydow** [comment]
Hi @corey-taylor, 

Thanks a lot for your edits on T018! :rocket:

I started with stream-lining the text format with the other notebooks, e.g.

- No title case in section headers
- Splitting cells per paragraph (makes reviews via ReviewNB easier)
- Using Markdown instead of HTML in text cells
- Resized all image files to the size they are supposed to have in the talktorial (we avoid to use HTML to resize images _in_ the talktorial)

Before I continue with the content review, could you please go through the notebook and 

- Remove HTML text formatting 
  - I fixed most if it in the _Theory_ part, however I did not remove the `<b>` and `<i>` tags outside of references, yet - maybe we can split our forces here
  - Let's do keep the HTML `<a id='similarity_theory'></a>` tags used to bookmark sections.
- Add a note to cells that need execution times longer than a couple of seconds (we usually add a note like "_Note_: Running the next cell may take a couple of minutes/xxx minutes/up to a minute" in a Markdown cell above the code cell)

Do ping me if in doubt regarding the text format. 
For quick checks, I usually have the template open in Jupyter Lab to remind myself of our formatting conventions: https://github.com/volkamerlab/teachopencadd/blob/master/teachopencadd/talktorials/T000_template/talktorial.ipynb

**Comment by corey-taylor** [comment]
Yup, wasn't sure whether to use html or markdown as the original had a mix of both, hence why I made it consistent at least. Cheers for clarifying and for providing the template.

**Comment by Armin-Ariamajd** [comment]
@AndreaVolkamer, @corey-taylor 

> * Same sell: What is drug score total? Is that a value that is returned by smina? maybe add explanation.

That's an average of three calculated drug-likeness scores: 
1) Lipinski's rule of 5 (normalized, i.e. 4 = 1, 3 = 0.75, 2 = 0.5, 1 = 0.25, 0 = 0)
2) QED (quantitative estimate of drug-likeness by Hopkins) calculated by RDKit using default parameters
3) QED calculated by implementing functions that fit the experimental data in the Hopkins paper

I think I 've explained it as comments in the code block where it's implemented (If I remember correctly it should be in the Ligand class)

> * Problems with nglview/widgets: Cell [33]: For me no image is shown when executing project1.Docking.visualize_all_poses() - I only see the drop down menu?

That's a known problem of NGLView with JupyterLab; In Jupyter notebook everything runs perfectly.

> * Cell [34]: Why do we dock the input ligand? Wasn't it co-crystallized in the first place?

It has, but I docked it as well in order to have a calculated reference value in order to compare it with the calculated affinities of the analogs (I thought it would be more accurate to compare calculated values instead of comparing one experimental value with calculated values).

> * cell [41]: The interaction affinity correlation plot is not entirely clear to me: what is on the x-axis? Maybe a bit too crowded? If a correlation between # interactions and affinity is plottet, I would expect rather a scatter plot with those two values as x and y?

The x-axis is simply ligand number, where ligands have been ordered by their binding affinities. It is supposed to show that as the binding affinity drops, there is no considerable decrease in the number of interactions. The left y-axis shows the binding affinity, and the right y-axis shows the number of interactions. Since three different number of interactions are plotted (i.e. total, H-bonds and hydrophobic), it couldn't be properly plotted as a scatter plot.


>   * Please check: When I run the project2, unfortunately, I get no results with better scores, but still `60149` shows as optimized ligand?

That's due to some randomness in the pipeline, so that the results might vary from run to run. Some of the randomness can be controlled (e.g. by providing a seed for Smina), but some cannot be controlled (e.g. PubChem does not always return the same analogs for a certain ligand, especially when the specified number of analogs is relatively small (in our case, I think I've set the value in the input specification to 30))

**Comment by Armin-Ariamajd** [comment]
@AndreaVolkamer , @dominiquesydow, @corey-taylor,

I pushed the finalized version. The changes are as follows:

* divided the ```utils.py``` file into 10 files (i.e. the 8 main classes plus Consts and LeadOptimizationPipeline), which are now stored in the ```utils``` folder. Also removed the helper classes from the main classes, and put them into another folder (```helpers```) in the ```utils``` folder. Since each file gives its helper class its own namespace, there was no need to have the static methods in a class, so now each helper-class is a module consisting of only functions. 

* corrected the error in the auto-generation of the DoGSiteScorer ligand-id, so now even if we don't enter the ligand-id in the input file, the correct id is generated and the binding-site detection works for all proteins.

* while testing the binding-site detection with other proteins, I also noticed some error in the parsing of the protein data (due to some PDB files having different formats), so I also corrected that.

* reducing the number of docking poses from 5 to 3 changed the calculated binding affinity of the best ligand in the second run, resulting in selection of another ligand with much lower affinity. Thus I kept the number of docking poses to 5. The scroll bar for the menu of the NGLViewer works fine for me, so there should be no problem. Note that I have set the height of the menu to be exactly equal to the height of the viewer on its right in order to avoid empty space at the bottom of the menu. So, the menu may seem long, but it never exceeds the height of the viewer. Nevertheless, if you like to change the number of poses to 3, you only have to modify the corresponding field (Docking - Number of Docking Poses per Ligand) in the input CSV file. However, then we would have to change the figure in the discussion.

* corrected the legends of the plot generated using the ```plot_interaction_affinity_correlation``` function.

* proof-read the whole notebook, fixed all errors and made the texts a bit more compact

* linked all headers back to table of contents, so now one can easily go back and forth between sections.

* changed the title to "Automated pipeline for lead optimization" .
* ran ```black -l 99``` 
* moved ```opencadd``` from in-house packages to 3rd-party packages
* removed all title cases in section headers
* split cells per paragraph

<br>

Remaining issues:
* the bullet points under "Aim of this talktorial" don't have uniform spacings. I've had fixed this before using HTML (i.e. with ```<br>```), since ```\\``` and ```\``` don't work in all environments.
* resizing the images has considerably lowered the quality of some figures. Maybe resize with another app/configs?

<br>

Note:
* the DoGSiteScorer API server was down, so I couldn't run the whole notebook all at once. Please test the whole notebook again when the server is back online, and let me know if there are any issues.

**Comment by Armin-Ariamajd** [comment]
@AndreaVolkamer, @dominiquesydow, @corey-taylor,

By the way, if you want to test the whole notebook while the DoGSiteScorer server is still offline, you can simply skip the binding site detection section, and manually run the following line before going to the next section (i.e. docking):

```project1.Protein.binding_site_coordinates = {'center': [16.55, 23.34, 1.31], 'size': [26.14, 26.14, 26.14]}```

Note that this coordinates is for the 3W32 structure, which is the default input structure in the pipeline.

For being able to run the ```run_pipeline``` function at the end of the tutorial you also need to comment out the binding site detection part of the ```run_pipeline``` function in the ```LeadOptimizationPipeline.py``` file under the ```utils``` folder, and again add the above line instead of it.

**Comment by dominiquesydow** [comment]
Hi @Armin-Ariamajd, thank you very much for fixing the issues, proof-reading the text, and the workaround while ProteinsPlus is down!

Questions
- [ ] I had removed the cross-references of sections as they are like this not functional in HTML on our website. We do have table of contents in (a) JupyterLab and (b) on our website. To avoid user issues telling us the links do not work, I am in favor of removing them again. Unless you have an idea how they could work also on our website, @Armin-Ariamajd?

More TODOs for myself
- [ ] Rename filenames conform with PEP8: https://www.python.org/dev/peps/pep-0008/#package-and-module-names
- [ ] No wildcard imports https://www.python.org/dev/peps/pep-0008/#toc-entry-10
- [ ] Check `utils` code

**Comment by Armin-Ariamajd** [comment]
> Hi @Armin-Ariamajd, thank you very much for fixing the issues, proof-reading the text, and the workaround while ProteinsPlus is down!
> 
> Questions
> 
> * [ ]  I had removed the cross-references of sections as they are like this not functional in HTML on our website. We do have table of contents in (a) JupyterLab and (b) on our website. To avoid user issues telling us the links do not work, I am in favor of removing them again. Unless you have an idea how they could work also on our website, @Armin-Ariamajd?
> 
> More TODOs for myself
> 
> * [ ]  Rename filenames conform with PEP8: https://www.python.org/dev/peps/pep-0008/#package-and-module-names
> * [ ]  No wildcard imports https://www.python.org/dev/peps/pep-0008/#toc-entry-10
> * [ ]  Check `utils` code

Hi @dominiquesydow,
you're welcome; I'm glad I could help!
Do you mean the links between the table of contents and the sections? I'm not sure why they shouldn't work on the website, since they are plain HTML code. Maybe it has something to do with the way you render it for the website (I believe you said you use Sphinx)?

**Comment by dominiquesydow** [comment]
Summary of changes described in the commit messages.

@Armin-Ariamajd: I figured out the problem with the cross-references on the website; the labels need to be exactly like the section title (joined by hyphens). Works now.

@AndreaVolkamer: NGLview works now under JupyterLab; problem was again that local files were loaded without `with open() as f`.

TODOs for myself:
- [ ] Rendering with `make html` is not working because of `from utils import LeadOp...` (works locally), all other `utils` imports work, too. Riddle me this. (works with the so beautiful `from teachopencadd.talktorials.T018_automated_cadd_pipeline.utils import LeadOptimizationPipeline`)
  ```
  ---------------------------------------------------------------------------
  ModuleNotFoundError                       Traceback (most recent call last)
  /tmp/ipykernel_19891/768423965.py in <module>
  ----> 1 from utils import LeadOptimizationPipeline
        2 
        3 project1 = LeadOptimizationPipeline(project_name="Project1_EGFR_CHEMBL328216")
  
  ModuleNotFoundError: No module named 'utils'
  ModuleNotFoundError: No module named 'utils'
  ```
- [ ] Freeze PubChem dataset
- [ ] Check again NBVAL checks (only did it here and there)
- [ ] Decide if we shorten the Theory by a lot; basically all that is already in the other notebooks

TODOs for later (open issue after PR merge)
- [ ] Go through FIXMEs in the code (generic exceptions _must_ go, missing `else`-clauses may be needed here and there to account for unexpected input)
- [ ] Remove the frozen binding site (marked with TODO in notebook and `utils`)
- [ ] Code comments should not live at the end of a line (must re-find that PEP8, I think there was one)
- [ ] Add attributes explicitly to classes like `LeadOptimizationPipeline`, somehow they are added dynamically, which I find very confusing
- [ ] Add missing docstrings

**Comment by dominiquesydow** [comment]
I reviewed the code without touching too much since we do not have proper unit tests; we will have cheap testing once the `nbval` tests are running.

I left TODOs/FIXMEs in the code to be dealt with in future revisions.

CIDs from round 1 are now frozen; CIDs from round 2 are not, yet, since I cannot reproduce the optimized ligand from round 2.
Since ProteinsPlus is still down, we are using a static binding site center:
```
{'center': [15.91, 32.33, 11.03], 'size': [24.84, 24.84, 24.84]}
```
This center results in the optimized ligand from round 1 as shown in Figure 9.

Still open:
- Freeze ligand from round 2
- Still problems with `make html`; does render but code cells through errors (it seems like sphinx runs? the notebook from the `docs` folder - why is this not a problem for any of the other notebooks?)
- Final HTML check at the very end

**Comment by Armin-Ariamajd** [comment]
Hi @dominiquesydow,

is there anything else I can maybe help you with?

And by the way, I'd say we change all mentions of 'helper class(es)' to 'helper module(s)', since they are no longer classes.

**Comment by dominiquesydow** [comment]
Hi @Armin-Ariamajd,

Thank you for your offer, that would be great indeed!

I won't work on this PR until Thursday. If you are free in the meantime, you could take over something from this list:

- > And by the way, I'd say we change all mentions of 'helper class(es)' to 'helper module(s)', since they are no longer classes.

  I agree, thanks for pointing that out!

- > Freeze ligand from round 2

  I have done this for round 1 as follows:

  ```python
  frozen_cids = [
      "65997",
      "2435",
      "57469",
      "5011",
      "62389",
      "11292933",
      "214347",
      "1530",
      "11256587",
      "1935",
      "62274",
      "53462",
      "84759",
      "62275",
      "6451164",
      "103148",
      "7019",
      "62805",
      "675",
      "5546",
  ]
  
  from utils import Consts
  
  analogs = {
      cid: Ligand(
          identifier_type=Consts.Ligand.InputTypes.CID,
          identifier_value=cid,
          ligand_output_path=project1.Specs.OutputPaths.similarity_search,
      )
      for cid in frozen_cids
  }
  project1.Ligand.analogs = analogs
  ```
  
  Could you please check
  - if this workaround is correct (the pipeline does run, so I assume it is)
  - how we could add this workaround elegantly for round 2

- You could also go ahead and resolve this PR's conflicts.

If you are making changes, could you please push them until Thursday morning or let me know to hold off for a bit longer so that we do not run into conflicts?

Thanks again for your help!

**Comment by dominiquesydow** [comment]
Thanks a lot, @Armin-Ariamajd, for solving so many open TODOs!!

I am summarizing here the last bits before we can merge :)

- [ ] Run notebook with Armin's changes to check if everything is running as planned (thank you for the round 2 freezing!!)
- [ ] Resolve PR conflicts (so that the CI starts running; hoping we won't run into too much trouble there)
- [ ] Render website (`make html` in `docs` folder) and resolve `utils` import issues
- [ ] Check rendered website for formatting issues; resolve them

**Comment by corey-taylor** [comment]
@dominiquesydow and I will knock these off today, hopefully.

**Comment by Armin-Ariamajd** [comment]
@dominiquesydow, @corey-taylor,

You're welcome; I'm not completely finished though.
If you would give me another day or two, there are some others corrections I'd like to make.
I'll then let you know when I'm finished.

**Comment by dominiquesydow** [comment]
Hi @Armin-Ariamajd, could you post a checklist of things that you still would like to do, please?

**Comment by Armin-Ariamajd** [comment]
Hi @dominiquesydow,

I'm in the middle of modifying the talktorials to run with the frozen CIDs, so there are some changes that are still not finalized and I haven't pushed yet. Also in the initial test after freezing the CIDs it seemed to me that the results are still not completely deterministic. So I have to take a closer look at that as well.

I'm in the middle of a lecture right now. Today is a bit busy day for me; I'll try to finalize and push the changes later today in the evening, or tomorrow evening at the latest, if that's okay with you.

**Comment by dominiquesydow** [comment]
Hi @Armin-Ariamajd,

Alrighty, we will wait :)

By tomorrow morning 
- please let us know if you are ready (then we pick up our open TODOs) _or_ 
- push what you have and post what the remaining open issues are (just to check in and decide if you want to continue on Friday or if we can split tasks between us by morning/afternoon/evening, ok?)

**Comment by Armin-Ariamajd** [comment]
Hi @dominiquesydow,

So far, I have:

* changed all mentions of "helper class(es)" to "helper module(s)"

* frozen the ligands for the second run as well, and changed the way how to use frozen ligands.
Your workaround was technically correct, but in my opinion there was a more elegant way to do it, so I changed the procedure for both runs as follows:
\
For each run, the list of frozen ligands is saved in a separate CSV file under the ```data``` folder (name ```FrozenPubchemQuery_project1.csv``` and ```FrozenPubchemQuery_project2.csv```).  Then I added a new parameter to the ```__init__``` function of the ```ligand_similarity_search``` class, called ```frozen_data_filepath```. This parameter has the dafault value ```None```, and so if it's not provided in the instantiation of the class, the similarity search will be performed using PubChem as before. However, when the parameter is provided, ```ligand_similarity_search``` will no longer perform a similarity search using PubChem, and instead builds the instance using the provided ligands in the CSV file.

* rolled back the binding site detection part to its original form, since Proteins.Plus is back online.

* proofread the whole talktorial again and corrected some wording and formatting.

* made some other small corrections (see commit comments)



The still remaining issues are:

* The pipeline (i.e. its docking part) is still not deterministic. It was very hard to pinpoint why, because for some ligands (mostly the analogs in the first run) the docking results are always the same, but for some other ligands (mostly the analogs in the second run, i.e. the automated run at the end) they're always different! That's why the result of the first run is always the same, but for the second run, the output ligand changes from run to run. 
\
So after a couple of hours I finally found out what the problem is; It's not in the docking part with Smina, but rather in the generation of 3D structures for docking, using Open Babel:
Before docking with Smina, the ```docking``` class calls the ```create_pdbqt_from_pdb_file``` and the ```create_pdbqt_from_smiles``` functions of the ```obabel``` helper module to generate 3D structures for the protein and the ligands, respectively. Both these functions then call the ```optimize_structure_for_docking``` function of the ```obabel``` module, which in turn calls the ```make3D``` function of the ```pybel``` module in the ```openbabel``` package. This is where the problem lies; The generation of 3D structures has inherent randomness in the algorithm, but the ```openbabel``` python API does not have the option to provide a seed. 
\
Apparently, for some ligands (and probably for the protein as well) the algorithm converges to the same coordinates every time, but for some other ligands, it does not.
\
This is a known issue with the ```openbabel``` package (see this posted issue on their GitHub: https://github.com/openbabel/openbabel/issues/1934).
\
Apparently the developers have provided a way to set a seed via a shell command, but I couldn't find a way to use this in the python API environment. 
At this point, the only way that comes to my mind for making the pipeline deterministic is to also freeze the 3d structures (i.e. the pdbqt files) generated before docking.




* When running the docking part, I now get the following warning from Open Babel:
```Open Babel Warning  in PerceiveBondOrders. Failed to kekulize aromatic bonds in OBMol::PerceiveBondOrders```
\
I get the warning for the protein and some ligands (but not all of them). It is from the functions ```create_pdbqt_from_pdb_file``` and ```create_pdbqt_from_smiles``` in the ```obabel``` helper module of the talktorial.
\
However, as far as I can tell, it doesn't have any effect on the docking results.
\
The only reason that comes to my mind which may have caused this warning to appear now and not before is that I have updated the ```biopandas``` package, which may have also updated the obabel package.
\
There is also this warning from the ```Structure``` module of ```opencadd.structure.core``` used in the function ```extract_molecule_from_pdb_file``` in the ```pdb``` helper module of the talktorial:
\
```861: DeprecationWarning: Using the last letter of the segid for the chainID is now deprecated and will be changed in 2.0. In 2.0, the chainID attribute will be used if it exists, or a placeholder value. warnings.warn("Using the last letter of the segid for the chainID "```


Please feel free to let me know if there is anything else I can help you with.

P.S. I could not resolve the conflicts, as they do not show up for me on my local machine.

**Comment by dominiquesydow** [comment]
Hi @Armin-Ariamajd,

Thanks a lot for all the work you put in!!

We will take it from here and try to resolve the last outstanding issues.

>     * frozen the ligands for the second run as well, and changed the way how to use frozen ligands.

I like the new setup!

>     * rolled back the binding site detection part to its original form, since Proteins.Plus is back online.

Perfect, thanks!
      
>       So after a couple of hours I finally found out what the problem is; It's not in the docking part with Smina, but rather in the generation of 3D structures for docking, using Open Babel:
>       Before docking with Smina, the `docking` class calls the `create_pdbqt_from_pdb_file` and the `create_pdbqt_from_smiles` functions of the `obabel` helper module to generate 3D structures for the protein and the ligands, respectively. Both these functions then call the `optimize_structure_for_docking` function of the `obabel` module, which in turn calls the `make3D` function of the `pybel` module in the `openbabel` package. This is where the problem lies; The generation of 3D structures has inherent randomness in the algorithm, but the `openbabel` python API does not have the option to provide a seed.
>       At this point, the only way that comes to my mind for making the pipeline deterministic is to also freeze the 3d structures (i.e. the pdbqt files) generated before docking.

Thanks for boiling the problem down to this. My first though was as well to freeze the PDBQT files. I will give some more thought.

>     * When running the docking part, I now get the following warning from Open Babel:
>       `Open Babel Warning  in PerceiveBondOrders. Failed to kekulize aromatic bonds in OBMol::PerceiveBondOrders`

Looking into this, thanks.
    
>       `861: DeprecationWarning: Using the last letter of the segid for the chainID is now deprecated and will be changed in 2.0. In 2.0, the chainID attribute will be used if it exists, or a placeholder value. warnings.warn("Using the last letter of the segid for the chainID "`

This is a warning from MDAnalysis < 2.0.0; since our environment requires >= 2.0.0 we should be fine. We'll check both warnings with a fresh `teachopencadd` environment.

**Comment by corey-taylor** [comment]
Can't see a way around freezing the pdbqt's. 

At least with something like Omega, the starting point is the same i.e. if you ask for 50 conformers in one run then 2000 in another, the first 50 of the latter should be identical. This is as opposed to Obabel where if you do multiple runs of 50, each batch of 50 will be slightly different. 

For rigid docking, this is a really irritating problem as, unlike MD, it's meant to be deterministic. Cheers for hunting it down, @Armin-Ariamajd.

**Comment by dominiquesydow** [comment]
Closing this PR; superseded by https://github.com/volkamerlab/teachopencadd/pull/179.

**Pull request closed without merging**
