### PR TITLE
T9. Replace pymol with nglview

### PR DESCRIPTION
**Pull request by jaimergp**
This PR replaces Pymol with nglview in T9

# Pending tasks

- [x] Render images for offline visualization

### CODE REVIEW

**Comment by dominiquesydow** [comment]
This is great! I have nothing to add :)

Shall we merge when all talktorials are refactored and make a new version out of it?

**Comment by jaimergp** [comment]
Shall I merge? I though you would do it!

**Comment by dominiquesydow** [comment]
There is still on open issue. 

With the current environment (rdkit 2019.03.4) I cannot see the images of the compounds in the last DataFrame, I only see a string "<img src="data:image/png;base64,iVBORw0KGgoAAA..." (ROMol column). 

Under the old environment the images are displayed (I think rdkit 2018.3.4).

I have not found a way yet to make the images appear again.

**Comment by dominiquesydow** [comment]
Ok then, I'll do it :)

**Pull request merged**
