### PR TITLE
T002: Fix usage of deprecated pandas function

### PR DESCRIPTION
**Pull request by mbackenkoehler**
This fixes the use of the deprecated `append` in the plotting function.

See issue #328

### CODE REVIEW

**Comment by mbackenkoehler** [comment]
Merging this solves #328

**Review by dominiquesydow — CHANGES_REQUESTED** [review]
Hi @mbackenkoehler, thank you for updating this notebook! 
As already raised for T018 in https://github.com/volkamerlab/teachopencadd/issues/334, the `rdkit` molecules do not currently show in the DataFrame. 
Could you please confirm this behavior locally? We have seen this issue with earlier `rdkit` versions but this was fixed on their end, not sure why this is showing up again.

**Comment by mbackenkoehler** [comment]
The screenshot in #334 is from a fresh local install using `devtools/test_env.yml`. So it should be rdkit 2021.09.5 (https://github.com/volkamerlab/teachopencadd/blob/3c6230d11fcd40ba8abcf3f81ec0472b314ef7bd/devtools/test_env.yml#L32)

**Comment by AndreaVolkamer** [comment]
This is an issue @greglandrum pointes us to and provded a solution for it, we need to insert this line after adding the molecule column to the dataframe: `PandasTools.RenderImagesInAllDataFrames(True)`
It is part of [PR #330](https://github.com/volkamerlab/teachopencadd/pull/330).

**Comment by mbackenkoehler** [comment]
So maybe Greg's PR can be merged first and then I update this branch?

**Comment by AndreaVolkamer** [comment]
@mbackenkoehler generally yes, but he only applied it to T004, but there are more instances that we need to fix (I've asked @hamzaibrahim21 to take care of this).

**Pull request merged**
