### PR TITLE
Add badges to README top

### PR DESCRIPTION
**Pull request by t-kimber**
# Badges

Add cool badges.

See https://shields.io/category/issue-tracking for full list.

### CODE REVIEW

**Comment by dominiquesydow** [comment]
Absolutely in favor of having this! 

Maybe we can add also: 

- Licence and version tag
- Closed/open issues; closed/open PRs
- @t-kimber's customized badge: https://img.shields.io/static/v1?label=socool&message=TeachOpenCADD&color=%3Cred%3E

**Comment by dominiquesydow** [comment]
@AndreaVolkamer could you please check if you are ok with the new badges: https://github.com/volkamerlab/teachopencadd/blob/5760e98b217e619ef2a730a12d9767abb78944da/README.md

**Comment by AndreaVolkamer** [comment]
@t-kimber and @dominiquesydow thanks both of you, they look great!

Two thoughts
* not entirely sure about the 'soocool' badge, although TOC is soocool ;)
* and while looking at the README, I was generally wondering if we should move a short intro sentence up, right below the header TeachOpenCADD. So the reader knows what to expect before the details including badges and new content follows (which on the laptop takes ~ half a page)

**Comment by t-kimber** [comment]
Thanks @AndreaVolkamer for your feedback !

- For the TOC badge itself, I suggest 2 alternatives: either no label, or project label, see screenshot. Maybe a bit more professional? :wink:
Screenshot 2021-06-01 at 09 19 54

- Concerning clarity for the reader, I would not necessarily add a sentence in the README since it is shown directly in the "about" section (see screenshot) but it's not my decision to make. @dominiquesydow and @AndreaVolkamer , your call :)
Screenshot 2021-06-01 at 09 20 04

**Comment by AndreaVolkamer** [comment]
@t-kimber thanks!
* I do have a slight preference for the one with 'project'
* How about we simply include the very same sentence as in 'About' below the TeachOpenCADD README title?

**Comment by t-kimber** [comment]
Done :)

**Comment by dominiquesydow** [comment]
Thank you, looks great to me! @t-kimber, this PR is ready to go from my side :)

**Pull request merged**
