### PR TITLE
Base branch for new kinase talkorials

### PR DESCRIPTION
**Pull request by dominiquesydow**
## Description
Add a new batch of ~7~ 6 kinase-focused talktorials (emphasizing on kinase similarity).

Per notebook, create new branch (`tk-t024-kinsim-seq`) and set up PR (T024 - Title). 

## Todos
- [x] [TK/DS] Add kinase-focused template #116
- [x] [DS] T023 - What is a kinase? #120
- [x] [TK] T024 - Kinase similarity: Sequence #117 
- [x] [DS] T025 - Kinase similarity: Structure (kinome-specific) #121
- [x] [DS] T026 - Kinase similarity: Interactions #122
- [x] [TK] T027 - Kinase similarity: Ligand profiles #118 
- [x] [TK/DS] T028 - Kinase similarity: Compare perspectives #123 
  - [ ] Try to formulate discussion more generalized so that notebook fits also for other kinase sets
- [x] ~[TK] T029 - Predicting affinity using kissim (ML) #119~
- [x] Formatting looks correctly on the Sphinx render (bold, italics, figure placing)
- [x] Regenerate READMEs
- [x] Check which input each notebook gets (UniProt, kinase name) - can we streamline with?
- [ ] [DS] After merging this PR, open small new PR where we update all relative image paths to URLs (otherwise problem with website I think); concerns T023 and T026

https://app.reviewnb.com/volkamerlab/teachopencadd/pull/115/

## Questions
- [ ] ???

## Status
- [ ] Ready to go

### CODE REVIEW

**Comment by AndreaVolkamer** [comment]
@t-kimber very nice notebook!

Some suggestions:
* maybe we can add a colorful sequence alignment fig (from KLIFS or so) to the theory?
* we could also mention the manning tree (phylogenetic tree by kinase sequence similarity), and that kinase similarities are often rated on sequence bases ... (similar as the sentence in T025 about structural similarity)
* we could comment on gaps in the alignment ('-')
* In the similarity equation 2: are there one too many '()' in the SM part?
* Function names: `identity_score`, `substitution_score`: They return an array, right? The actual score is later calculated in sequence similarity, consider renaming ->  `residue_wise_identity`,  `identity_score_array` or ....
* The intro to distance vs. similarity matrix could potentially be moved up to the theory part

**Comment by AndreaVolkamer** [comment]
@dominiquesydow very nice notebook!

Some suggestions:
* structures -> structures_df? Actually that might be a general question, for me it is mostly easier to work with new code, if the name reveals the type.
* Do we want a real copy here (`structure_distance_matrix.copy()`)? 
```
# Copy distance matrix to kinase matrix
kinase_distance_matrix = structure_distance_matrix
```
* Unstacking the matrix and grouping is a bit like magic, but it works ;)
* Just wondering if it would be worth showing the residue-wise similarity between two kinases/structures in 3D?

**Comment by AndreaVolkamer** [comment]
@dominiquesydow very nice notebook T026, again.

Some suggestions:
* Theory: I would rather put here an interaction fingerprint example figure from KLIFS, Figure 1 was already shown in T025, you could simply refer to there if you want to exemplify the 85 residue content in KLIFS?
* Not entirely clear what is meant by "Let's define our kinases of interest **and all their synonyms**", in the end we want exactly the 9 kinases, it might be confusing why there are currently more, but one ends up with the correct 9. 
* Maybe add a short hint what KLIFS ids are (here or in T025)?
* I believe we do not need the `# Cast string to list of "0" and "1"` cell, I commented it out for now, please double check.
* Same copy question as in T25 `# Copy distance matrix to kinase matrix`
* I like the discussion point on ifp comparison, though one might wonder if sth similar would apply for kissim-based comparison as well? (tbd)

**Comment by AndreaVolkamer** [comment]
@t-kimber again, great work on T027!

Some suggestions:
* Maybe a figure in the theory part might be nice/helpful, exact content tbd, maybe some data plotted on kinmap (or so for kinase promiscuity)
* Should we name activity_value -> pIC50 in the dataframe to make the choice more explicit
* One could put the kinase of interest part at the same position as in the previous notebooks for comparability?
* Note I changed the helper function to take uniprot ids instead of kinase_names as input, because otherwise the functions used the global dict name_to_uniprot (maybe double check if it is consistent)
* I currently get an error when running the cell to beautify the table (not sure what the exact problem is though `ValueError: zero-size array to reduction operation fmin which has no identity?`)
* Would be nice to also have a matrix of common actives and/or of common tested compounds between the kinase pairs so the user gets a better overview of what the fraction actually means, i.e. 0.5 could stand for 2 common actives/4 common tested as well as for 500/1000. tbd

**Comment by AndreaVolkamer** [comment]
@t-kimber found the issue for the long runtime of T024: the sequences were queries from KLIFS in the loop for calculating the matrix, took this out and used the pre-stored sequences instead.

**Comment by AndreaVolkamer** [comment]
@t-kimber and @dominiquesydow I only quickly went over T028, since I believe it is still more WIP

Only two comments:
* Note I changed in the sequence nb (T024) that the filename contains the information if substitution or identity score are used. All is fine when the identity version is used. But the calculated substitution sequence matrix is not symmetric, which will break the code. Since the substitution matrix itself is symmetric, so should the distance matrix be, or? Could you please look into this?
* Concerning the visualization helper function: One could already introduce them at the beginning when showing the first example and use them there. Then later they could be used together for the final composed plot (which could become a function on its own again)?

**Comment by t-kimber** [comment]
> @t-kimber found the issue for the long runtime of T024: the sequences were queried from KLIFS in the loop for calculating the matrix, took this out and used the pre-stored sequences instead.

I had to revert it back since we are now using a csv file which contains the kinase selection (and doesn't include the sequences), but I added a warning that the cell might take a little bit of time to execute.

**Comment by dominiquesydow** [comment]
@t-kimber I have reviewed T027 and love it! There are no open TODOs for you from my side :)

---

Changes (that also may be relevant other talktorials) I made include:

- Fix section levels
- Update TOCs where necessary
- Change `activity_dataframe` to `activity_df` to be in-line with other `_df` variables
- Always use `df["bla"]` instead of `df.bla` notation to be in-line with other talktorials
- Always refer to other talktorials with __Talktorial Txxx__ (no links, use __ not **) to be in-line with other talktorials
- Use f-string trick `print(f"{'Some text' : <30}")` instead of `print(f"Some text: \t\t")` to align print text
- Adding KinMap and ChEMBL refs

**Comment by t-kimber** [comment]
**T023** for my review:

# Content review

* Potential labels or categories (e.g. machine learning, small molecules, online APIs): XXXXXXXX
* One line summary: XXXXXXXXXX
* [ ] The table of contents reflects the talktorial story-line; order of #, ##, ### headers is correct
* [ ] URLs are linked with meaningful words, instead of pasting the URL directly or linking words like `here`.
* [ ] I have spell-checked the notebook
* [ ] Images have enough resolution to be rendered with quality, without being _too_ heavy.
* [ ] All figures have a description
* [ ] Markdown cell content is still in-line with code cell output (whenever results are discussed)
* [ ] I have checked that cell outputs are not incredibly long (this applies also to `DataFrames`)
* [ ] Formatting looks correctly on the Sphinx render (bold, italics, figure placing)

# Code review

* Time it took to execute (approx.):
* [ ] Variable and function names follow snake case rules (e.g. `a_variable_name` vs `aVariableName`)
* [ ] Spacing follows PEP8 (run Black on the code cells if needed)
* [ ] Code line are under 99 characters each (run `black -l 99`)
* [ ] Comments are useful and well placed
* [ ] There are no unpythonic idioms like `for i in range(len(list))` (see slides)
* [ ] All 3rd party dependencies are listed at the top of the notebook
* [ ] I have marked all code cell with output referenced in markdown cells with the label `# NBVAL_CHECK_OUTPUT`
* [ ] I have identified potential candidates for a code refactor / useful functions
* [ ] All `import ...` lines are at the top (practice part) cell, ordered by standard library / 3rd party packages / our own (`teachopencadd.*`)
* [ ] I have update the relative paths to absolute paths.
* List here unfamiliar libraries you find in the imports and their intended use:

**Comment by AndreaVolkamer** [comment]
> > @t-kimber found the issue for the long runtime of T024: the sequences were queried from KLIFS in the loop for calculating the matrix, took this out and used the pre-stored sequences instead.
> 
> I had to revert it back since we are now using a csv file which contains the kinase selection (and doesn't include the sequences), but I added a warning that the cell might take a little bit of time to execute.

The [fix](https://github.com/volkamerlab/teachopencadd/pull/115/commits/952da33d078f558d60f244ff29d790cae8e34584) would still apply, just maybe needs to be updated to get the key (i.e. kinase name) from the df info now instead. 
Besides the efficiency gain, the fix would also be cleaner, since we do not use a global dictionary in the function.

**Comment by t-kimber** [comment]
Wow wow wow, no typos in __T025__, one single black error and that's it! How I wish all reviews could be so easy! @dominiquesydow making life painless :) 

_NB_: TODO check HTML rendering at the end.

**Comment by dominiquesydow** [comment]
@t-kimber, I think our **T023**-**T027** talktorials are in top shape now! 

I just pushed the results of our discussion on **T028** - it is ready for review now.

**Comment by t-kimber** [comment]
@AndreaVolkamer, the notebooks T023-T028 are ready!! We will do a final sphinx rendering check after your review.

**Comment by dominiquesydow** [comment]
@AndreaVolkamer if you'd like to leave comments, please find here again the link to ReviewNB:
https://app.reviewnb.com/volkamerlab/teachopencadd/pull/115/

**Comment by AndreaVolkamer** [comment]
**T023** looks GREAT!
@dominiquesydow I only encountered small issues when running the code that might be easy to fix for you or maybe I need to update sth?
*  KLIFS binding site figure is not showing
* cell 6 throws an error `KeyError: 'kinase.uniprot'`
* cell 7 also throws an error: `ImportError: cannot import name 'PocketKlifs' from 'opencadd.structure.pocket'`
* in cell 7: maybe mention where the number `4367` comes from?

**Comment by dominiquesydow** [comment]
Hi @AndreaVolkamer, 
Thank you for your review! 

Quick back-check re the import errors:
Did you use a fresh TOC environment?

```
mamba env create -f https://raw.githubusercontent.com/volkamerlab/TeachOpenCADD/master/devtools/other-conda-envs/users_env.yml
```

**Comment by AndreaVolkamer** [comment]
**T024** is GREAT as well!
@t-kimber only two questions and one change to be double checked, please
* the sequence logo was produced based on 9 kinases, right? So technically there can only be 9 different AS per residue position, just wondering where all the letters come from?
* great that you fixed the symmetry issue. Just wondering a) what the issue was and b) that most likely triggered the translate/scale matrix. Is there a link that we could add explaining this?
* please double check my changes in `def pairwise_kinase_similarities`: I added the sequences to the input parameters and have function operate directly on kinase_names, which were set before to be the same as klifs_names

**Comment by AndreaVolkamer** [comment]
**T025** GREAT as well.

@dominiquesydow only one very minor understanding question to the discussion. I'm not sure I fully unterstand this very last point, tbd:

> We only compare here the two closest structures per kinase pair, although we have — at least for kinases such as EGFR and CDK2 — much more structural data available. Aggregating multiple structures is a reasonable strategy but has two disadvantages:
> * Some kinases have much higher coverage than others, leading to an imbalance in information content.
> * Aggregated kinase fingerprints may cause too much averaging, making pairwise kinase comparison noisier.

**Comment by AndreaVolkamer** [comment]
And another GREAT notebook **T026** 

@dominiquesydow 
* I only applied mainly the same small textual changes as in T025
* One tiny thing to adapt: Quiz question 3: I believe there is no dendrogram any more in the notebook ;)
> What is the difference between the distances that we show in the heatmap and the dendrogram?

**Comment by AndreaVolkamer** [comment]
GREAT work on **T027**

Note, I mainly added a few notes/discussion points.

@t-kimber nothing to do :)

**Comment by AndreaVolkamer** [comment]
Dear @dominiquesydow and @t-kimber, GREAT work on all notebooks.

**T028**
* Besides minor textual and variable name adaptions,
* I mainly changed that in the final visualization, the heatmap is based on the similarity (not the distance matrix). To me this is easier to interpret, because then higher values in the heatmap, represent closer realtionships in the dendrogram.

**Comment by dominiquesydow** [comment]
> And another GREAT notebook **T026**
> 
> @dominiquesydow
> 
> * I only applied mainly the same small textual changes as in T025
> * One tiny thing to adapt: Quiz question 3: I believe there is no dendrogram any more in the notebook ;)
> 
> > What is the difference between the distances that we show in the heatmap and the dendrogram?

@AndreaVolkamer thank you very much for your review!! 
Good job spotting this, thanks! I moved the question to T028 (summary talktorial) and added "What are the advantages and disadvantages of describing kinase similarity with interaction fingerprints?" to T026 (IFP talktorial).

**Comment by t-kimber** [comment]
> **T024** is GREAT as well! @t-kimber only two questions and one change to be double checked, please
> 
> * the sequence logo was produced based on 9 kinases, right? So technically there can only be 9 different AS per residue position, just wondering where all the letters come from?
> * great that you fixed the symmetry issue. Just wondering a) what the issue was and b) that most likely triggered the translate/scale matrix. Is there a link that we could add explaining this?
> * please double check my changes in `def pairwise_kinase_similarities`: I added the sequences to the input parameters and have function operate directly on kinase_names, which were set before to be the same as klifs_names

Thanks for the review!

Concerning your comments:

- Sequence logo: TBD
- The [minmaxscaler](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.MinMaxScaler.html#sklearn.preprocessing.MinMaxScaler)  from sklearn does scaling along features, or axis. In this case, it doesn't retain symmetry. My initial fix was to apply a simple minmax scaler on all entries of the matrix. But another issue arised with this: the Blosum matrix doesn't have all diagonal entries set to one. This means that if you compute the similarity between the same two words (for example "AVOLKAMER"), then the self-similarity would not be the highest score (here 1.) So to find a nice workaround, I used the other rescaling. I haven't checked the literature to see how/if people do it in another way. So in effect, there is no link at the moment, just a simple math workaround.
- Concerning the `def pairwise_kinase_similarities` function: I changed it again to make it (hopefully) clearer: we use instead a dictionary. In this case, the one defined at the top of the practical part which queries KLIFS only n=9 times (n= the number of kinases of interest) with the kinase name as key and kinase sequence as value.

**Comment by t-kimber** [comment]
> GREAT work on **T027**
> 
> Note, I mainly added a few notes/discussion points.
> 
> @t-kimber nothing to do :)

@AndreaVolkamer Thank you!
I fixed a few typos and put numbers in math mode. Otherwise, it's ready!

**Comment by t-kimber** [comment]
Dear @dominiquesydow and @AndreaVolkamer ,
I finished checking the HTML rending for this set of notebooks. Going through them a month later made me love them even more <3
The CI seems to be failing, but besides this _small_ (wink wink) issue, this PR is ready to be merged IMO!
What a nice project it has been :)

**Comment by dominiquesydow** [comment]
> Dear @dominiquesydow and @AndreaVolkamer , I finished checking the HTML rending for this set of notebooks. Going through them a month later made me love them even more <3 

Thank you, @t-kimber, for making them HTML-ready :heart: I share your sentiment towards our kinase talktorials :)

> The CI seems to be failing, but besides this _small_ (wink wink) issue, this PR is ready to be merged IMO! 

That made me laugh _a lot_, given that I am trying to fix the CI fails for T018 just now :D

> What a nice project it has been :)

Absolutely agreed! :)

**Comment by t-kimber** [comment]
Just mentioning here that the CI is now passing (even though it doesn't look like it ;) ) and that this PR is officially ready for the world. Hallelujah!

**Comment by t-kimber** [comment]
Added library:  `dataframe_image`, see https://github.com/dexplo/dataframe_image 
Why? Convert pandas styler dataframe to png.
Conda installation:
`conda install -c conda-forge dataframe_image`

**Review by t-kimber — APPROVED** [review]
Approve? Ohh yes, 100% !! ❤️  💟  😍

**Comment by t-kimber** [comment]
The kinase similarity collection is ready, with thumbnails and everything 🎉

**Comment by dominiquesydow** [comment]
@t-kimber just triggering the CI again, so that we know our notebooks have not picked up any dependency conflicts in the meantime (because external packages were updated or something like this).

**Pull request merged**
