### PR TITLE
Fixes for protonation of protein and binding site detection

### PR DESCRIPTION
**Pull request by corey-taylor**
## Description
Small fixes for T018 pipeline issues and CI Python 3.9 issues. 

## TODOs
- [x] commands in obabel helper function are run in the wrong order and result in docking to a structure that has no hydrogens
- [x] issue with number of positional arguments when running binding site detection class.
- [ ] Under Python 3.9: Check if ´interactions´ variable is dict or a dict embedded in list (Python 3.9) - make sure we work with the dict. See [error message](https://github.com/volkamerlab/teachopencadd/runs/5461111349?check_suite_focus=true#step:8:163).

## Status
- [ ] Ready to go

### CODE REVIEW

**Review by dominiquesydow — APPROVED** [review]
Hi @corey-taylor, thanks a lot for fixing this - I reran the CI a couple of times, seems to be URL timeouts here and there. Let's merge this and check if the website will be rendered alright (do not quite understand the Docs fail).

**Comment by dominiquesydow** [comment]
@corey-taylor, did the results change? If so, we need to rerun the notebook, right?

**Comment by corey-taylor** [comment]
> Hi @corey-taylor, thanks a lot for fixing this - I reran the CI a couple of times, seems to be URL timeouts here and there. Let's merge this and check if the website will be rendered alright (do not quite understand the Docs fail).

Yep, agreed with this. If the site renders fine then we'll just put it down to gremlins in the machine or something.

> @corey-taylor, did the results change? If so, we need to rerun the notebook, right?

The results changed for me, yes. I didn't actually run the input ligand in the notebook, I ran 3W32's co-crystallised ligand but you'd imagine they'd be quite different. I'll re-run it and commit.

**Comment by corey-taylor** [comment]
@dominiquesydow Oh wait a sec, didn't the notebook work better when you or @AndreaVolkamer ran it last time, given I use Linux?

**Comment by dominiquesydow** [comment]
@corey-taylor, on second thought: in the notebook, we are testing for the resulting compounds from projects 1 and 2:
```
project1.OptimizedLigands.output
# NBVAL_CHECK_OUTPUT
---
[<Ligand CID: 11292933>]
```
and
```
project2.OptimizedLigands.output
# NBVAL_CHECK_OUTPUT
---
[<Ligand CID: 28693>]
```

With your changes, we are still getting the same compounds (we know that because the CI is not failing except for the Python 3.9 setup). Does this make sense to you? To be honest, I would have expected to see changes - but hey, happy about stable results :)

---

With that said, running the notebook under 3.9 indeed reproduces the CI error also locally. I won't be able to look into this tonight but will try to pick this up tomorrow.

**Comment by corey-taylor** [comment]
> @corey-taylor, on second thought: in the notebook, we are testing for the resulting compounds from projects 1 and 2:
> 
> ```
> project1.OptimizedLigands.output
> # NBVAL_CHECK_OUTPUT
> ---
> [<Ligand CID: 11292933>]
> ```
> 
> and
> 
> ```
> project2.OptimizedLigands.output
> # NBVAL_CHECK_OUTPUT
> ---
> [<Ligand CID: 28693>]
> ```
> 
> With your changes, we are still getting the same compounds (we know that because the CI is not failing except for the Python 3.9 setup). Does this make sense to you? To be honest, I would have expected to see changes - but hey, happy about stable results :)

Ordinarily I'd be quite worried about getting consistent results when changing something as major as the protonation of the entire protein. Certainly the ranking of compounds changed for me, although this is obviously a very small library and a fairly apolar pocket compared to other kinases so maybe that's why.

> 
> With that said, running the notebook under 3.9 indeed reproduces the CI error also locally. I won't be able to look into this tonight but will try to pick this up tomorrow.

For your info, nothing special about my setup. I run 3.9.7 in BunsenLabs Linux (used theTeachOpenCADD yaml). I certainly don't see the AttributeErrors so I'm not sure why the Ubuntu version is being tripped.

**Comment by dominiquesydow** [comment]
@jaimergp could you please take a look at why conda is failing for the Python 3.7 unit tests?
E.g. https://github.com/volkamerlab/teachopencadd/runs/5716919708?check_suite_focus=true

**Comment by dominiquesydow** [comment]
Merging this PR - T018 runs successfully under Py3.7 and 3.9 after workaround as outlined in PR description.

Remark on CI:
- Docs CI still failing, addressed in https://github.com/volkamerlab/teachopencadd/pull/217
- Unit tests CI still fails for T018, I think with a connection error (in the SI section), most probably not an issue on our end: 
  ```
    ValueError: Fetching results from DoGSiteScorer API failed.
    Expected key id not found in the response.
    The response message is as follows: {'message': 'Loading PDB file'}
  ```
- Unit tests CI for MacOS: Full conda install failed (at least the imports seem to not exist) - probably rerun will resolve this. If not, open new issue and PR to fix this.

**Pull request merged**
