### PR TITLE
[2023.05.2-base] DL edition

### PR DESCRIPTION
**Pull request by AndreaVolkamer**
## Description
TeachOpenCADD DL edition.

Comments from @dominiquesydow: 
- I started listing the new talktorials and (new) DL-related dependencies. 
- Please check if correct and add any missing new dependencies per talktorial (I listed `tensorflow` here although already part of the env since this package causes us a great deal of trouble for over a year now and tbh I'd love to get rid of it, tbd.)
- General note: Each new notebook should add as few new deps as possible (at least as long as we do not have a per-notebook env and CI).
- Extended MacOS/M1 chip instructions: https://github.com/volkamerlab/teachopencadd/pull/301
- Check out the new contributor guide at https://projects.volkamerlab.org/teachopencadd/contribute.html once https://github.com/volkamerlab/teachopencadd/pull/274 is merged

## Todos

- [x] https://github.com/volkamerlab/teachopencadd/pull/314 ([nb](https://github.com/volkamerlab/teachopencadd/tree/gg-033-molecular_representations/teachopencadd/talktorials/T033_molecular_representations)) @gerritgr 
- [x] https://github.com/volkamerlab/teachopencadd/pull/287 ([nb](https://github.com/volkamerlab/teachopencadd/blob/pk-034-gnns/teachopencadd/talktorials/T034_gnn_property_prediction/talktorial.ipynb)) @PaulaKramer
  - DL deps: `torch` and `torch_geometric `
- [x] https://github.com/volkamerlab/teachopencadd/pull/320 ([nb](https://github.com/volkamerlab/teachopencadd/blob/at-035-rnns/teachopencadd/talktorials/T035_rnns/talktorial.ipynb)) @azmtag 
- [x] https://github.com/volkamerlab/teachopencadd/pull/286 ([nb](https://github.com/volkamerlab/teachopencadd/blob/mb-036-uncertainty-estimation/teachopencadd/talktorials/T036_uncertainty_estimation/talktorial.ipynb)) @mbackenkoehler
  - DL deps: `tensorflow` -- which minimum version?
- [x] https://github.com/volkamerlab/teachopencadd/pull/326 ([nb](https://github.com/volkamerlab/teachopencadd/blob/jg-034-e3-equivariant-gnn/teachopencadd/talktorials/T037_e3_equivariant_gnn/talktorial.ipynb)) @joschka-gross
  - DL deps: `torch` and `torch_geometric` and `torch_scatter`??
- [x] https://github.com/volkamerlab/teachopencadd/pull/290 ([nb](https://github.com/volkamerlab/teachopencadd/blob/rj-038-dti/teachopencadd/talktorials/T038_protein_ligand_interaction_prediction/talktorial.ipynb)) @Old-Shatterhand
  - DL deps: `torch` and `torch_geometric`
  - _`torch_geometric` dependencies: `torch_scatter`, `torch_sparse`, `torch_cluster`, `torch_spline_conv` (without these, `torch_geometric` might not work._ (Added by @Old-Shatterhand)
- [x] https://github.com/volkamerlab/teachopencadd/pull/357 change DL notebook ordering
## Questions
- [ ] Question1

## Status
- [ ] Ready to go

### CODE REVIEW

**Comment by mbackenkoehler** [comment]
I am currently switching from `tensorflow` to `torch` on my talktorial. That's more consistent with the other ones and by far the more common choice for our audience, I believe.  I am planning on essentially lifting the pytorch tutorial code instead of T022. The version should not really matter.

**Comment by joschka-gross** [comment]
`torch_scatter` is not installed explicitly but as a mandatory dependency for `torch_geometric`. Although unlikely, I can not outrule that this might change in future releases, but I think we agreed on pinning the `torch_geometric` version anyway, so this should be fine.

**Comment by mbackenkoehler** [comment]
We should collect release todos for the notebooks somewhere.

Take T033 as an example: There are several links to other talktorials which is going to link talktorials on the master branch.

**Comment by dominiquesydow** [comment]
@AndreaVolkamer what is your current plan with this PR regarding the merge? First merging https://github.com/volkamerlab/teachopencadd/pull/345 and then this?

**Comment by mbackenkoehler** [comment]
I changed the target to `dev`. We can test out the environment and the merge in general before the DL_edition release.

**Pull request merged**
