### PR TITLE
Add T008-T010 updates from t011-base branch to master

### PR DESCRIPTION
**Pull request by dominiquesydow**
## Description

We have fixed issues with T008 and T010 (and updated T009 according to changes in T008) in PR https://github.com/volkamerlab/teachopencadd/pull/74. Since this PR will not be merged for quite some more time, let's add the updates for the "old" notebooks already now to `master` (T008 and T010 are _not_ running).

## Todos

Please refer to issue https://github.com/volkamerlab/teachopencadd/issues/90 for a detailed description of the `pypdb`-related issues in these notebooks.

Summary:
- T008 and T010: Use `biotite` instead of `pypdb` to query PDB IDs matching a list of criteria
- T008 and T010: Restructure theory part to include `biotite` _and_ `pypdb`
- T009: Rerun with new structure in T008

## Questions

None.

## Status

- [x] Ready to go

### CODE REVIEW

**Comment by dominiquesydow** [comment]
@jaimergp, could you please take a quick look at the failing conda packaging here? 

In this PR, I want to update the T008 and T010 notebooks, whose updates are otherwise stuck in our big `t011-base` branch while the notebooks on `master` continue to be broken. 

The [last commit on `master`](https://github.com/volkamerlab/teachopencadd/runs/2516791944) has a passing conda packaging CI, so (a) I am wondering why it is failing here and (b) if we have to fix it in this PR or not.

Thank you :)

**Comment by jaimergp** [comment]
I don't see issues with the conda packaging here (looking at Pytest, ubuntu, 3.6). It complains about other stuff: changed cell results, new locations for the KLIFS endpoint...

**Comment by dominiquesydow** [comment]
@jaimergp, could you please check [here](https://github.com/volkamerlab/teachopencadd/runs/2999651706) and [here](https://github.com/volkamerlab/teachopencadd/pull/109/checks?check_run_id=3006798224) (CI on the same commit)? Do you have ideas why the process is killed?

**Comment by dominiquesydow** [comment]
Hi @jaimergp :)

Can we merge this PR even if the "CI / Conda package" is not working currently? 
In other words, does the current `master` branch currently need the conda packaging or does this functionality come into place with the `t011-base` branch?

I am asking because it would be great to have a working version of T008 and T010 on the `master` branch, now that the `t011-base` branch merge will take some more time.

**Comment by jaimergp** [comment]
Hey! I'd say we can merge and add the conda package in a new PR!

**Pull request merged**
