### PR TITLE
T8: Exchange pymol with superposer+nglview

### PR DESCRIPTION
**Pull request by dominiquesydow**
## Description

Remove `pymol` from notebook, use `superposer` for alignment and `nglview` for visualization instead.

## ToDos

- [x] Remove `pymol`
- [x] Align structures with `superposer`
- [x] Move each text paragraph/section to separate Markdown cell
- [x] Sort imports, remove `*` import for `pypdb`
- [x] NGL visualization empty in current notebook because local installation not working > Fixed.
- [x] T8 output files are not added to GH: Rerun T9 and check if results change with new data. > Manually checked results, only differ slightly, therefore do not rerun T9.

## Questions

- [x] @jaimergp: Currently, alignment for complex (protein+ligand). How to do the alignment for the protein only, but still get the transformed ligand coordinates? > Protein residues only are considered during sequence alignment, so no problem here.
- [x] @dominiquesydow: Comparison of aligned ligands based on `pymol` and `superposer` using PyMol GUI: Alignment very similar, but ligands from `pymol` show aromatic rings, from `superposer` do not. Check files and check effect on T9 `rdkit` pharmacophore perception. > Not a problem, `rdkit` molecules are the same.
   - With `superposer`: 
        alt text
  - With `pymol`: 
        alt text

## Status

- [x] Ready to go

### CODE REVIEW

**Comment by dominiquesydow** [comment]
@jaimergp, can you help me out with this question (see also PR text):

> Currently, alignment for complex (protein+ligand). How to do the alignment for the protein only, but still get the transformed ligand coordinates?

**Comment by jaimergp** [comment]
Superposer does not consider ligands at all for now, so it should work right away, I think.

**Comment by jaimergp** [comment]
> Alignment very similar, but ligands from pymol show aromatic rings, from superposer do not

This might be a defect in MDAnalysis PDB input/output, that "forgets" bond orders?

**Comment by dominiquesydow** [comment]
Let me just paste here the code I am using to make sure:

```python
complexes = [Structure.from_atomgroup(structure.select_atoms(f"protein or resname {ligand}")) for structure, ligand in zip(structures, pairs.values())]
complexes
results = align(complexes, method=METHODS["mda"])
```

So even if the ligand is part of the MDanalysis, it will be ignored because we are doing a sequence alignment and that involves the protein only. Do I get that right?

**Comment by jaimergp** [comment]
That's correct!

**Comment by dominiquesydow** [comment]
Thanks!

**Comment by dominiquesydow** [comment]
FYI, @AndreaVolkamer, @jaimergp, will get back to this PR in one week (need to fix my local nglview installation and rerun T9).

**Comment by dominiquesydow** [comment]
T8 is ready for merging from my side. 

The alignment with `superposer` is pretty similar to `pymol` - pharmacophore results in T9 do not change (I checked locally, will not rerun T9 in this round, this will be done during refactoring anyways).
 
@jaimergp, @AndreaVolkamer - does one of you want to review the changes?

**Comment by jaimergp** [comment]
This is ready to merge now! I just made sure everything was working correctly on my setup and while doing that couldn't help but apply small refactors here and there :)

**Comment by AndreaVolkamer** [comment]
@dominiquesydow and @jaimergp the notebook looks great, thanks for updating. Just two things:
* You could add a link to the superposer repo, so the interested use can find more information there
* To me the visualized protein alignment doesn't actually look right? (these are all egfr structures, so the aligned structures should look more alike?

**Comment by jaimergp** [comment]
I can't reproduce the misalignment locally but just in case I am making sure we are using opencadd.structure.superposition instead of superposer directly -- that alone seems to fix it although the code is technically the same.

I have also updated T10 accordingly. The images now look ok!

**Comment by jaimergp** [comment]
Oops, sorry about that T9 thing. I was checking whether it contained alignments too or just nglview 😬

**Comment by dominiquesydow** [comment]
No, no, that is all on me ([here](https://github.com/volkamerlab/TeachOpenCADD/pull/32/commits/b1f500cbc3772e9746433dd18c7afa0117a17315)), although I planned on explicitly NOT updating T9 as stated in the PR:
> Manually checked results, only differ slightly, therefore do not rerun T9.

Well :)

**Comment by dominiquesydow** [comment]
@jaimergp - another question, is 
```python
logger = logging.getLogger("superposer")
```
still up to date on `opencadd`?

**Comment by jaimergp** [comment]
Hm, you are right! It should be

```python
logger = logging.getLogger("opencadd")
```

That's why we are getting so many warnings again, because I am not silencing them now due to that mismatch. Nice spotting!

**Comment by dominiquesydow** [comment]
And are we referencing `superposer` (used in text) or `opencadd.structure.superposition` (used in code) now?

Currently:
> Molecular superposition with Python: ([`superposer`](https://github.com/volkamerlab/superposer))

Or are they maybe the same under the hood?

I am asking because I would add the reference also to T8.

**Comment by dominiquesydow** [comment]
@jaimergp - just in case we are both working on this right now - I am updating the logger and the references :)

**Comment by jaimergp** [comment]
Oops, yep, we should refer to `opencadd` now. I think I fixed some of the `superposer` references in one of the two notebooks (T8 or T10, not sure), if that helps.

**Comment by dominiquesydow** [comment]
@jaimergp and @AndreaVolkamer, thanks for your work here - I am merging this PR now.

**Pull request merged**
