### PR TITLE
T010 review

### PR DESCRIPTION
**Pull request by dominiquesydow**
# Details

* Talktorial ID: 010
* Title: Binding site similarity and off-target prediction
* Original authors:  Angelika Szengel, Marvis Sydow, Richard Gowers, Jaime Rodríguez-Guerra, Dominique Sydow
* Reviewer(s): Dominique Sydow, Mareike Leja
* Date of review: 2020-09-21
* [ReviewNB link](https://app.reviewnb.com/volkamerlab/TeachOpenCADD/pull/44/files/)

# Content review

* Potential labels or categories (e.g. machine learning, small molecules, online APIs): _binding site comparison, binding site similarity, structural alignment, off-target prediction, EGFR, kinase, imatinib, PDB_
* One line summary: _Similar binding sites are likely to bind the same ligand, causing unwanted side affects of a drug. Binding site similarity can be used to predict potential off-targets or alterate applications of a drug (drug repositioning)._
* [x] The table of contents reflects the talktorial story-line; order of #, ##, ### headers is correct
* [x] URLs are linked with meaningful words, instead of pasting the URL directly or linking words like `here`.
* [x] I have spell-checked the notebook
* [x] Images have enough resolution to be rendered with quality, without being _too_ heavy.
* [x] All figures have a description
* [x] Markdown cell content is still in-line with code cell output (whenever results are discussed)
* [x] I have checked that cell outputs are not incredibly long (this applies also to `DataFrames`)
* [x] Formatting looks correctly on the Sphinx render (bold, italics, figure placing)

# Code review

* Time it took to execute (approx.): _About 4 minutes (calculating RMSD between 8 proteins takes 3 min (`calc_rmsd_matrix`))_
* [x] Variable and function names follow snake case rules (e.g. `a_variable_name` vs `aVariableName`)
* [x] Spacing follows PEP8 (run Black on the code cells if needed)
* [ ] Code line are under 99 characters each (run `black -l 99`)  > will be checked for all notebooks at the end.
* [x] Comments are useful and well placed
* [x] There are no unpythonic idioms like `for i in range(len(list))` (see slides)
* [x] All 3rd party dependencies are listed at the top of the notebook
* [x] I have marked all code cell with output referenced in markdown cells with the label `# TODO: CI`
* [x] I have identified potential candidates for a code refactor / useful functions
* [x] All `import ...` lines are at the top (practice part) cell, ordered by standard library / 3rd party packages / our own (`teachopencadd.*`)
* [x] I have update the relative paths to absolute paths.
Please add the following lines to the top of the notebook and use those paths
  ```python
  HERE = Path(_dh[-1])
  DATA = HERE / "data"
  ```
* List here unfamiliar libraries you find in the imports and their intended use: _None._

## Questions

- [x] This comes from `opencadd.structure.superposition` > `MDAnalysis` - shall we silence this or is this indeed something that needs to be updated? > Add `warnings.simplefilter("ignore")`
image
- [x] This warning comes when clustering the binding site RMDS matrix - `seaborn` specific. > Add `warnings.simplefilter("ignore")`
image  
* [x] Use `cprofile` to profile the RMSD calculation > `MDAnalysis.core.selection.StringSelection` is slow (`fnmatch` used to select atoms); I added an issue on `opencadd.structure.superposition`, maybe we can optimize our code to be a bit faster here: https://github.com/volkamerlab/opencadd/issues/47

### CODE REVIEW

**Comment by dominiquesydow** [comment]
This issue is addressed in this PR: https://github.com/volkamerlab/TeachOpenCADD/issues/20

**Comment by dominiquesydow** [comment]
Hi @Mika-Le, this talktorial is ready for your review. Thank you!

**Comment by jaimergp** [comment]
We might want to seed the random module here just in case:

```python
def seed_everything(seed=1234):
    import random
    import os
    import numpy as np
    random.seed(seed)
    os.environ["PYTHONHASHSEED"] = str(seed)
    np.random.seed(seed)
```

**Comment by dominiquesydow** [comment]
Thanks!

Where do I call that function? At the beginning of my Practical section?


We decided on 22 as our default seed - or did we end with 1234 (in case we care)?

**Comment by jaimergp** [comment]
> We decided on 22 as our default seed - or did we end with 1234 (in case we care)?

It doesn't matter as long as it's the same in every notebook _run_ (it could be different across notebooks). That said, let's use 22. `1234` comes from the library I "borrowed" that code from 😬

**Comment by jaimergp** [comment]
In issue https://github.com/volkamerlab/TeachOpenCADD/issues/20 variable names say `pbd`, not `pdb`. I haven't checked if this has been addressed here, but just in case!

**Comment by dominiquesydow** [comment]
@jaimergp, I added the random module - the matrix stayed the same to before. 
The notebook is ready to go.

**Comment by jaimergp** [comment]
Nice. I'll add a note to move that function to the library and reuse it in other notebooks too.

**Pull request merged**
