### PR TITLE
Docs CI: switch to linkinator

### PR DESCRIPTION
**Pull request by mbackenkoehler**
## Description
Switch from `broken-link-checker` to `linkinator`. The former seems to be dead.

## Todos
Notable points that this PR has either accomplished or will accomplish.
- [x] Check all dead links

## Questions
- [x] What's the reasoning behind the excludes?

## Status
- [x] Ready to go

### CODE REVIEW

**Comment by mbackenkoehler** [comment]
Merging this will resolve #333

There are a lot of dead links around, which need to be fixed manually. I will open a separate issue for that.

**Comment by dominiquesydow** [comment]
Hi @mbackenkoehler, thanks a lot for this update - ready to go from my side.

**Review by dominiquesydow — APPROVED** [review]

**Review by dominiquesydow — CHANGES_REQUESTED** [review]
Hi @mbackenkoehler, 
As there are a couple of PRs that depend on each other in order to get the CI pass, could you please branch off `master` something like `ci-fixes-base` and then merge all the open PRs to that branch first? 
Basically, so that we see the full CI pass before merging everything to `master`.  @AndreaVolkamer, please do intervene if you'd like to go ahead in another way.

**Comment by AndreaVolkamer** [comment]
@dominiquesydow thanks that is a good idea, @mbackenkoehler can you coordinate this?

**Comment by mbackenkoehler** [comment]
> Hi @mbackenkoehler, As there are a couple of PRs that depend on each other in order to get the CI pass, could you please branch off `master` something like `ci-fixes-base` and then merge all the open PRs to that branch first? Basically, so that we see the full CI pass before merging everything to `master`. @AndreaVolkamer, please do intervene if you'd like to go ahead in another way.

Maybe we should use a general dev branch for that. Since there are also some non-CI issues that should be done and merged simoultaneously. @dominiquesydow Do we want to use the existing `dev` branch?

**Pull request merged**
