### PR TITLE
T10: Remove Pymol dependencies

### PR DESCRIPTION
**Pull request by jaimergp**
Take over PR #7, started by @richardjgowers. Following text is copied from his PR:

> Started to remove pymol from notebook 10, turned out more difficult than expected because there's protein alignment using pymol too.
Used biotite package for sequence alignment, then MDAnalysis for coordinate alignment, from what I could tell, there isn't a clean way to sequence & coordinate align in one package.....
Got down to the rmsd matrix calculation, there's still some binding pocket rmsd to do still.
My first PDB ID ended up being the "worst" one, so I think my alignment results ended up being worse because all proteins were aligned to the worst PDB ID....

### CODE REVIEW

**Comment by jaimergp** [comment]
Ok, I have assessed the current situation and have concluded that working on this notebook right now does not make much sense. Current limitations will be solved by `structuralalignment`. I will work on that instead and then replace the cells here so they use it. The implementation found here is just a mockup of what the `matchmaker` method contains:

* It assumes that the protein is a single chain
* It neglects the existence of ligands

**Comment by jaimergp** [comment]
Ok, that should do it. RMSDs are not as low as in pymol, but still serves the purpose! Let me know what you think!

**Comment by dominiquesydow** [comment]
Hi @jaimergp, thanks! Will do the review tomorrow and get back to you.

**Comment by dominiquesydow** [comment]
@jaimergp, thank you so much for moving this notebook from `pymol` to `superposer` & `nglview`! I really enjoyed going over this talktorial.

I have not run the notebook locally yet (having installation problems at the moment, probably on my end), will report back once I was able to set up everything.

**Comment by dominiquesydow** [comment]
> I have not run the notebook locally yet (having installation problems at the moment, probably on my end), will report back once I was able to set up everything.

Will document my steps here in case others encounter the same:

`conda env create -f environment.yml 
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - openbabel==2.4`

I am running conda 4.7.10 (latest version 4.8.3), maybe the error occurs because my conda version is too late, trying to update (failing at the moment).

**Comment by jaimergp** [comment]
Oh yes, it's `openbabel 2.4.1`. Saw that error yesterday at `volkamerlab/plipify`. Pushing this little change in case you want to try now.

**Comment by dominiquesydow** [comment]
Excellent, I can install the conda environment now, thanks!

**Comment by dominiquesydow** [comment]
@jaimergp - I fixed my `nglview` problem (thanks for the tip to this resource: https://github.com/SBRG/ssbio/wiki/Troubleshooting#issues-with-the-jupyter-notebook)

Notebook runs with some smaller issues as described above - congrats on `superposer`, it's really cool to have this instead of my lengthily and not-so-readable pymol code!

**Comment by jaimergp** [comment]
<p><code>nglview</code>  might have some issues though... I think we should leave it there.</p>

---

 <a href='https://app.reviewnb.com/volkamerlab/TeachOpenCADD/pull/10/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jaimergp** [comment]
<p>I removed it because it was only useful for PyMol.</p>

---

 <a href='https://app.reviewnb.com/volkamerlab/TeachOpenCADD/pull/10/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jaimergp** [comment]
<p>Nope, not needed. Thanks!</p>

---

 <a href='https://app.reviewnb.com/volkamerlab/TeachOpenCADD/pull/10/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jaimergp** [comment]
<p>There were more but they are fixed now, thanks for the tip!</p>

---

 <a href='https://app.reviewnb.com/volkamerlab/TeachOpenCADD/pull/10/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jaimergp** [comment]
<p>Yeah, sorry, this is a mistake. Reverting the verbose printing now!</p><p> </p><blockquote>Also, is&nbsp;<code>align</code>&nbsp;modifying&nbsp;<code>proteins</code>' coordinates in-place?</blockquote><p>Yes!</p>

---

 <a href='https://app.reviewnb.com/volkamerlab/TeachOpenCADD/pull/10/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jaimergp** [comment]
<p>I think you might an older nglview version? I don't have that problem :/</p>

---

 <a href='https://app.reviewnb.com/volkamerlab/TeachOpenCADD/pull/10/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jaimergp** [comment]
<p>Fixed!</p>

---

 <a href='https://app.reviewnb.com/volkamerlab/TeachOpenCADD/pull/10/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jaimergp** [comment]
@dominiquesydow, I have tagged superposer to current behavior, readded the `3fw1` filtering, and now also one more ID. Can you please check if the last cells are good enough content-wise? I feel that I can add some more explanation but I am not very inspired today...

**Comment by dominiquesydow** [comment]
Hi @jaimergp, thanks a lot for the update! 
I commented on two parts of the notebook text, it would be great to hear what you think.

I will need to look at some structure pairs later this afternoon - do you want me to make a branch from here + PR for suggestions on the notebook?

**Comment by jaimergp** [comment]
<p>Oh, I didn't modify the overall wording here, IIRC. [<a href="https://github.com/volkamerlab/TeachOpenCADD/blob/master/talktorials/10_binding_site_similarity/T10_off-targets.ipynb" target="_blank">See original</a>] I only replaced Pymol&gt;NglView.</p><p> </p><p> </p>

---

 <a href='https://app.reviewnb.com/volkamerlab/TeachOpenCADD/pull/10/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jaimergp** [comment]
<p>You are spot on here. I'll use your paragraph verbatim!</p>

---

 <a href='https://app.reviewnb.com/volkamerlab/TeachOpenCADD/pull/10/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by dominiquesydow** [comment]
> Oh, I didn't modify the overall wording here, IIRC. [[See original](https://github.com/volkamerlab/TeachOpenCADD/blob/master/talktorials/10_binding_site_similarity/T10_off-targets.ipynb)] I only replaced Pymol>NglView.
> 
> [View entire conversation](https://app.reviewnb.com/volkamerlab/TeachOpenCADD/pull/10/discussion/) on ReviewNB

Nice, so I am commenting on my past self, nice!

**Comment by jaimergp** [comment]
> do you want me to make a branch from here + PR for suggestions on the notebook?

Oh, I see I did this from my fork. Let me merge this to a branch here and you can commit here directly.

**Comment by dominiquesydow** [comment]
For the sake of completeness: I adde

**Pull request merged**
