### PR TITLE
T020 - Analyzing molecular dynamics simulations

### PR DESCRIPTION
**Pull request by Mika-Le**
# Details

* Talktorial ID: 020
* Title: Analyzing Molecular Dynamics Simulations
* Original authors: Mareike Leja
* Reviewer(s): David Schaller
* Date of review:

# Content review

* Potential labels or categories (e.g. machine learning, small molecules, online APIs): XXXXXXXX
* One line summary: XXXXXXXXXX
* [x] The table of contents reflects the talktorial story-line; order of #, ##, ### headers is correct
* [x] URLs are linked with meaningful words, instead of pasting the URL directly or linking words like `here`.
* [ ] I have spell-checked the notebook
* [x] Images have enough resolution to be rendered with quality, without being _too_ heavy.
* [x] All figures have a description
* [x] Markdown cell content is still in-line with code cell output (whenever results are discussed)
* [x] I have checked that cell outputs are not incredibly long (this applies also to `DataFrames`)
* [x] Formatting looks correctly on the Sphinx render (bold, italics, figure placing)

# Code review

* Time it took to execute (approx.):
* [x] Variable and function names follow snake case rules (e.g. `a_variable_name` vs `aVariableName`)
* [x] Spacing follows PEP8 (run Black on the code cells if needed)
* [x] Code line are under 99 characters each (run `black -l 99`)
* [x] Comments are useful and well placed
* [x] There are no unpythonic idioms like `for i in range(len(list))` (see slides)
* [x] All 3rd party dependencies are listed at the top of the notebook
* [x] I have marked all code cell with output referenced in markdown cells with the label `# TODO: CI`
* [ ] I have identified potential candidates for a code refactor / useful functions
* [ ] All `import ...` lines are at the top (practice part) cell, ordered by standard library / 3rd party packages / our own (`teachopencadd.*`)
* [x] I have update the relative paths to absolute paths.
* List here unfamiliar libraries you find in the imports and their intended use:

### CODE REVIEW

**Comment by dominiquesydow** [comment]
@Mika-Le - your talktorial's final index will be `T020`. Could you please at some point update this PR according to that (let me know if you need help)?

**Comment by schallerdavid** [comment]
@Mika-Le,

wuhuu, I finally made it. Can you have a final look if you agree with the changes I made?

David

**Comment by AndreaVolkamer** [comment]
@Mika-Le really well done, I included only small textual changes.
I have very few smaller questions that I will address using ReviewNB.

**Comment by Mika-Le** [comment]
Hi @AndreaVolkamer your and @jaimergp comments are addressed. Maybe you have already seen it I commited 2 weeks ago, but forgot to ping you. 
Details are in Review NB.

**Comment by jaimergp** [comment]
Thanks @Mika-Le! I re-read it and it. is. awe. some! Merged!

**Pull request merged**
